<?php
/**
 * @file
 * @ingroup LinkedDataStorage
 */

/*  Copyright 2010, ontoprise GmbH
*   This file is part of the LinkedData-Extension.
*
*   The LinkedData-Extension is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 3 of the License, or
*   (at your option) any later version.
*
*   The LinkedData-Extension is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/**
 * This file initializes and deletes all MySQL database tables and
 * triple store content that is used by the Linked Data Extension. 
 *
 * @author Thomas Schweitzer
 *
 */

global $lodgIP;
require_once $lodgIP . '/storage/LOD_DBHelper.php';

/**
 * This class encapsulates methods that care about the database tables and 
 * triple store graphs of the LinkedData extension.
 * 
 * @author Thomas Schweiter 
 *
 */
class LODStorageSQL {

	/**
	 * Initializes the database tables of the Linked Data extensions.
	 * These are:
	 *
	 */
	public function initDatabaseTables() {

		print "Setting up the Linked Data Extension...\n";

		$db =& wfGetDB( DB_MASTER );

		$verbose = true;
		LODDBHelper::reportProgress("Setting up LinkedData ...\n",$verbose);

		// lod_mapping_persistence:
		//		persistence of mappings that are defined in wiki articles
		$table = $db->tableName('lod_mapping_persistence');

		LODDBHelper::setupTable($table, array(
			'mapping_id'	=> 'INT(8) UNSIGNED NOT NULL AUTO_INCREMENT',
            'source' 		=> 'Text CHARACTER SET utf8 COLLATE utf8_bin',
            'target' 		=> 'Text CHARACTER SET utf8 COLLATE utf8_bin',
            'mapping_text' 	=> 'Text CHARACTER SET utf8 COLLATE utf8_bin'),
		$db, $verbose, 'mapping_id, source(128), target(128)');
		LODDBHelper::reportProgress("   ... done!\n",$verbose);
		
		print "   ... done!\n";
		
		return true;

	}
	
	public function dropDatabaseTables() {
		
		print("Deleting all database content and tables generated by the Linked Data Extension ...\n\n");
		
		print("Deleting source definitions...");
		LODAdministrationStore::getInstance()->deleteAllSourceDefinitions();
		print("done.\n");
		
		
		print("All data removed successfully.\n");
	}

}