//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="AddInBinding", Namespace="urn:addin")]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(Comment))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(PropertyPair))]
public partial class addinService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback getCategoriesOperationCompleted;
    
    private System.Threading.SendOrPostCallback getPropertiesOperationCompleted;
    
    private System.Threading.SendOrPostCallback getTitlePropertiesOperationCompleted;
    
    private System.Threading.SendOrPostCallback getTitlesOperationCompleted;
    
    private System.Threading.SendOrPostCallback validateOperationCompleted;
    
    private System.Threading.SendOrPostCallback saveNewMailOperationCompleted;
    
    private System.Threading.SendOrPostCallback addCategoryOperationCompleted;
    
    private System.Threading.SendOrPostCallback getPageInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback getCategories2OperationCompleted;
    
    private System.Threading.SendOrPostCallback getProperties2OperationCompleted;
    
    private System.Threading.SendOrPostCallback getTitleProperties2OperationCompleted;
    
    private System.Threading.SendOrPostCallback getTitles2OperationCompleted;
    
    private System.Threading.SendOrPostCallback authenticateOperationCompleted;
    
    private System.Threading.SendOrPostCallback saveNewMail2OperationCompleted;
    
    private System.Threading.SendOrPostCallback addCategory2OperationCompleted;
    
    private System.Threading.SendOrPostCallback getPageInfo2OperationCompleted;
    
    private System.Threading.SendOrPostCallback getCategories2DetailOperationCompleted;
    
    private System.Threading.SendOrPostCallback getPossibleFormsOperationCompleted;
    
    private System.Threading.SendOrPostCallback savePageToFormOperationCompleted;
    
    private System.Threading.SendOrPostCallback createFormTemplateOperationCompleted;
    
    private System.Threading.SendOrPostCallback savePageBasicOperationCompleted;
    
    private System.Threading.SendOrPostCallback setPageFormsOperationCompleted;
    
    private System.Threading.SendOrPostCallback getFormFieldValuesOperationCompleted;
    
    /// <remarks/>
    public addinService(string url)
    {
        this.Url = url + "index.php?action=wsmethodaddin";
    }
    
    /// <remarks/>
    public event getCategoriesCompletedEventHandler getCategoriesCompleted;
    
    /// <remarks/>
    public event getPropertiesCompletedEventHandler getPropertiesCompleted;
    
    /// <remarks/>
    public event getTitlePropertiesCompletedEventHandler getTitlePropertiesCompleted;
    
    /// <remarks/>
    public event getTitlesCompletedEventHandler getTitlesCompleted;
    
    /// <remarks/>
    public event validateCompletedEventHandler validateCompleted;
    
    /// <remarks/>
    public event saveNewMailCompletedEventHandler saveNewMailCompleted;
    
    /// <remarks/>
    public event addCategoryCompletedEventHandler addCategoryCompleted;
    
    /// <remarks/>
    public event getPageInfoCompletedEventHandler getPageInfoCompleted;
    
    /// <remarks/>
    public event getCategories2CompletedEventHandler getCategories2Completed;
    
    /// <remarks/>
    public event getProperties2CompletedEventHandler getProperties2Completed;
    
    /// <remarks/>
    public event getTitleProperties2CompletedEventHandler getTitleProperties2Completed;
    
    /// <remarks/>
    public event getTitles2CompletedEventHandler getTitles2Completed;
    
    /// <remarks/>
    public event authenticateCompletedEventHandler authenticateCompleted;
    
    /// <remarks/>
    public event saveNewMail2CompletedEventHandler saveNewMail2Completed;
    
    /// <remarks/>
    public event addCategory2CompletedEventHandler addCategory2Completed;
    
    /// <remarks/>
    public event getPageInfo2CompletedEventHandler getPageInfo2Completed;
    
    /// <remarks/>
    public event getCategories2DetailCompletedEventHandler getCategories2DetailCompleted;
    
    /// <remarks/>
    public event getPossibleFormsCompletedEventHandler getPossibleFormsCompleted;
    
    /// <remarks/>
    public event savePageToFormCompletedEventHandler savePageToFormCompleted;
    
    /// <remarks/>
    public event createFormTemplateCompletedEventHandler createFormTemplateCompleted;
    
    /// <remarks/>
    public event savePageBasicCompletedEventHandler savePageBasicCompleted;
    
    /// <remarks/>
    public event setPageFormsCompletedEventHandler setPageFormsCompleted;
    
    /// <remarks/>
    public event getFormFieldValuesCompletedEventHandler getFormFieldValuesCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:addin/getCategories", RequestNamespace="urn:addin", ResponseNamespace="urn:addin")]
    [return: System.Xml.Serialization.SoapElementAttribute("getCategoriesReturn")]
    public string[] getCategories() {
        object[] results = this.Invoke("getCategories", new object[0]);
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetCategories(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getCategories", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string[] EndgetCategories(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public void getCategoriesAsync() {
        this.getCategoriesAsync(null);
    }
    
    /// <remarks/>
    public void getCategoriesAsync(object userState) {
        if ((this.getCategoriesOperationCompleted == null)) {
            this.getCategoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCategoriesOperationCompleted);
        }
        this.InvokeAsync("getCategories", new object[0], this.getCategoriesOperationCompleted, userState);
    }
    
    private void OngetCategoriesOperationCompleted(object arg) {
        if ((this.getCategoriesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getCategoriesCompleted(this, new getCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:addin/getProperties", RequestNamespace="urn:addin", ResponseNamespace="urn:addin")]
    [return: System.Xml.Serialization.SoapElementAttribute("getPropertiesReturn")]
    public string[] getProperties() {
        object[] results = this.Invoke("getProperties", new object[0]);
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetProperties(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getProperties", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string[] EndgetProperties(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public void getPropertiesAsync() {
        this.getPropertiesAsync(null);
    }
    
    /// <remarks/>
    public void getPropertiesAsync(object userState) {
        if ((this.getPropertiesOperationCompleted == null)) {
            this.getPropertiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPropertiesOperationCompleted);
        }
        this.InvokeAsync("getProperties", new object[0], this.getPropertiesOperationCompleted, userState);
    }
    
    private void OngetPropertiesOperationCompleted(object arg) {
        if ((this.getPropertiesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getPropertiesCompleted(this, new getPropertiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:addin/getTitleProperties", RequestNamespace="urn:addin", ResponseNamespace="urn:addin")]
    [return: System.Xml.Serialization.SoapElementAttribute("getTitlePropertiesReturn")]
    public PropertyPair[] getTitleProperties(string title) {
        object[] results = this.Invoke("getTitleProperties", new object[] {
                    title});
        return ((PropertyPair[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetTitleProperties(string title, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getTitleProperties", new object[] {
                    title}, callback, asyncState);
    }
    
    /// <remarks/>
    public PropertyPair[] EndgetTitleProperties(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((PropertyPair[])(results[0]));
    }
    
    /// <remarks/>
    public void getTitlePropertiesAsync(string title) {
        this.getTitlePropertiesAsync(title, null);
    }
    
    /// <remarks/>
    public void getTitlePropertiesAsync(string title, object userState) {
        if ((this.getTitlePropertiesOperationCompleted == null)) {
            this.getTitlePropertiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTitlePropertiesOperationCompleted);
        }
        this.InvokeAsync("getTitleProperties", new object[] {
                    title}, this.getTitlePropertiesOperationCompleted, userState);
    }
    
    private void OngetTitlePropertiesOperationCompleted(object arg) {
        if ((this.getTitlePropertiesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getTitlePropertiesCompleted(this, new getTitlePropertiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:addin/getTitles", RequestNamespace="urn:addin", ResponseNamespace="urn:addin")]
    [return: System.Xml.Serialization.SoapElementAttribute("getTitlesReturn")]
    public string[] getTitles(string[] categoryTitles) {
        object[] results = this.Invoke("getTitles", new object[] {
                    categoryTitles});
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetTitles(string[] categoryTitles, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getTitles", new object[] {
                    categoryTitles}, callback, asyncState);
    }
    
    /// <remarks/>
    public string[] EndgetTitles(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public void getTitlesAsync(string[] categoryTitles) {
        this.getTitlesAsync(categoryTitles, null);
    }
    
    /// <remarks/>
    public void getTitlesAsync(string[] categoryTitles, object userState) {
        if ((this.getTitlesOperationCompleted == null)) {
            this.getTitlesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTitlesOperationCompleted);
        }
        this.InvokeAsync("getTitles", new object[] {
                    categoryTitles}, this.getTitlesOperationCompleted, userState);
    }
    
    private void OngetTitlesOperationCompleted(object arg) {
        if ((this.getTitlesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getTitlesCompleted(this, new getTitlesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:addin/validate", RequestNamespace="urn:addin", ResponseNamespace="urn:addin")]
    [return: System.Xml.Serialization.SoapElementAttribute("validateReturn")]
    public ValidateType validate() {
        object[] results = this.Invoke("validate", new object[0]);
        return ((ValidateType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginvalidate(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("validate", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public ValidateType Endvalidate(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ValidateType)(results[0]));
    }
    
    /// <remarks/>
    public void validateAsync() {
        this.validateAsync(null);
    }
    
    /// <remarks/>
    public void validateAsync(object userState) {
        if ((this.validateOperationCompleted == null)) {
            this.validateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidateOperationCompleted);
        }
        this.InvokeAsync("validate", new object[0], this.validateOperationCompleted, userState);
    }
    
    private void OnvalidateOperationCompleted(object arg) {
        if ((this.validateCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.validateCompleted(this, new validateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:addin/saveNewMail", RequestNamespace="urn:addin", ResponseNamespace="urn:addin")]
    [return: System.Xml.Serialization.SoapElementAttribute("saveNewMailReturn")]
    public string saveNewMail(string subject, string sender, string[] receivers, string[] ccs, System.DateTime sentDate, string basedMailPage, string action, string[] categories, string body, string[] attachments) {
        object[] results = this.Invoke("saveNewMail", new object[] {
                    subject,
                    sender,
                    receivers,
                    ccs,
                    sentDate,
                    basedMailPage,
                    action,
                    categories,
                    body,
                    attachments});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsaveNewMail(string subject, string sender, string[] receivers, string[] ccs, System.DateTime sentDate, string basedMailPage, string action, string[] categories, string body, string[] attachments, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("saveNewMail", new object[] {
                    subject,
                    sender,
                    receivers,
                    ccs,
                    sentDate,
                    basedMailPage,
                    action,
                    categories,
                    body,
                    attachments}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndsaveNewMail(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void saveNewMailAsync(string subject, string sender, string[] receivers, string[] ccs, System.DateTime sentDate, string basedMailPage, string action, string[] categories, string body, string[] attachments) {
        this.saveNewMailAsync(subject, sender, receivers, ccs, sentDate, basedMailPage, action, categories, body, attachments, null);
    }
    
    /// <remarks/>
    public void saveNewMailAsync(string subject, string sender, string[] receivers, string[] ccs, System.DateTime sentDate, string basedMailPage, string action, string[] categories, string body, string[] attachments, object userState) {
        if ((this.saveNewMailOperationCompleted == null)) {
            this.saveNewMailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveNewMailOperationCompleted);
        }
        this.InvokeAsync("saveNewMail", new object[] {
                    subject,
                    sender,
                    receivers,
                    ccs,
                    sentDate,
                    basedMailPage,
                    action,
                    categories,
                    body,
                    attachments}, this.saveNewMailOperationCompleted, userState);
    }
    
    private void OnsaveNewMailOperationCompleted(object arg) {
        if ((this.saveNewMailCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.saveNewMailCompleted(this, new saveNewMailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:addin/addCategory", RequestNamespace="urn:addin", ResponseNamespace="urn:addin")]
    [return: System.Xml.Serialization.SoapElementAttribute("addCategoryReturn")]
    public bool addCategory(string categoryName) {
        object[] results = this.Invoke("addCategory", new object[] {
                    categoryName});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginaddCategory(string categoryName, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("addCategory", new object[] {
                    categoryName}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndaddCategory(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void addCategoryAsync(string categoryName) {
        this.addCategoryAsync(categoryName, null);
    }
    
    /// <remarks/>
    public void addCategoryAsync(string categoryName, object userState) {
        if ((this.addCategoryOperationCompleted == null)) {
            this.addCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddCategoryOperationCompleted);
        }
        this.InvokeAsync("addCategory", new object[] {
                    categoryName}, this.addCategoryOperationCompleted, userState);
    }
    
    private void OnaddCategoryOperationCompleted(object arg) {
        if ((this.addCategoryCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.addCategoryCompleted(this, new addCategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:addin/getPageInfo", RequestNamespace="urn:addin", ResponseNamespace="urn:addin")]
    [return: System.Xml.Serialization.SoapElementAttribute("pageInfo")]
    public PageInfo getPageInfo(string title) {
        object[] results = this.Invoke("getPageInfo", new object[] {
                    title});
        return ((PageInfo)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetPageInfo(string title, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getPageInfo", new object[] {
                    title}, callback, asyncState);
    }
    
    /// <remarks/>
    public PageInfo EndgetPageInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((PageInfo)(results[0]));
    }
    
    /// <remarks/>
    public void getPageInfoAsync(string title) {
        this.getPageInfoAsync(title, null);
    }
    
    /// <remarks/>
    public void getPageInfoAsync(string title, object userState) {
        if ((this.getPageInfoOperationCompleted == null)) {
            this.getPageInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPageInfoOperationCompleted);
        }
        this.InvokeAsync("getPageInfo", new object[] {
                    title}, this.getPageInfoOperationCompleted, userState);
    }
    
    private void OngetPageInfoOperationCompleted(object arg) {
        if ((this.getPageInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getPageInfoCompleted(this, new getPageInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:addin/getCategories2", RequestNamespace="urn:addin", ResponseNamespace="urn:addin")]
    [return: System.Xml.Serialization.SoapElementAttribute("getCategories2Return")]
    public StringsType getCategories2(AuthenticationType auth) {
        object[] results = this.Invoke("getCategories2", new object[] {
                    auth});
        return ((StringsType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetCategories2(AuthenticationType auth, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getCategories2", new object[] {
                    auth}, callback, asyncState);
    }
    
    /// <remarks/>
    public StringsType EndgetCategories2(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((StringsType)(results[0]));
    }
    
    /// <remarks/>
    public void getCategories2Async(AuthenticationType auth) {
        this.getCategories2Async(auth, null);
    }
    
    /// <remarks/>
    public void getCategories2Async(AuthenticationType auth, object userState) {
        if ((this.getCategories2OperationCompleted == null)) {
            this.getCategories2OperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCategories2OperationCompleted);
        }
        this.InvokeAsync("getCategories2", new object[] {
                    auth}, this.getCategories2OperationCompleted, userState);
    }
    
    private void OngetCategories2OperationCompleted(object arg) {
        if ((this.getCategories2Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getCategories2Completed(this, new getCategories2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:addin/getProperties2", RequestNamespace="urn:addin", ResponseNamespace="urn:addin")]
    [return: System.Xml.Serialization.SoapElementAttribute("getProperties2Return")]
    public StringsType getProperties2(AuthenticationType auth) {
        object[] results = this.Invoke("getProperties2", new object[] {
                    auth});
        return ((StringsType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetProperties2(AuthenticationType auth, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getProperties2", new object[] {
                    auth}, callback, asyncState);
    }
    
    /// <remarks/>
    public StringsType EndgetProperties2(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((StringsType)(results[0]));
    }
    
    /// <remarks/>
    public void getProperties2Async(AuthenticationType auth) {
        this.getProperties2Async(auth, null);
    }
    
    /// <remarks/>
    public void getProperties2Async(AuthenticationType auth, object userState) {
        if ((this.getProperties2OperationCompleted == null)) {
            this.getProperties2OperationCompleted = new System.Threading.SendOrPostCallback(this.OngetProperties2OperationCompleted);
        }
        this.InvokeAsync("getProperties2", new object[] {
                    auth}, this.getProperties2OperationCompleted, userState);
    }
    
    private void OngetProperties2OperationCompleted(object arg) {
        if ((this.getProperties2Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getProperties2Completed(this, new getProperties2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:addin/getTitleProperties2", RequestNamespace="urn:addin", ResponseNamespace="urn:addin")]
    [return: System.Xml.Serialization.SoapElementAttribute("getTitleProperties2Return")]
    public PropertyPairsType getTitleProperties2(AuthenticationType auth, string title) {
        object[] results = this.Invoke("getTitleProperties2", new object[] {
                    auth,
                    title});
        return ((PropertyPairsType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetTitleProperties2(AuthenticationType auth, string title, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getTitleProperties2", new object[] {
                    auth,
                    title}, callback, asyncState);
    }
    
    /// <remarks/>
    public PropertyPairsType EndgetTitleProperties2(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((PropertyPairsType)(results[0]));
    }
    
    /// <remarks/>
    public void getTitleProperties2Async(AuthenticationType auth, string title) {
        this.getTitleProperties2Async(auth, title, null);
    }
    
    /// <remarks/>
    public void getTitleProperties2Async(AuthenticationType auth, string title, object userState) {
        if ((this.getTitleProperties2OperationCompleted == null)) {
            this.getTitleProperties2OperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTitleProperties2OperationCompleted);
        }
        this.InvokeAsync("getTitleProperties2", new object[] {
                    auth,
                    title}, this.getTitleProperties2OperationCompleted, userState);
    }
    
    private void OngetTitleProperties2OperationCompleted(object arg) {
        if ((this.getTitleProperties2Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getTitleProperties2Completed(this, new getTitleProperties2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:addin/getTitles2", RequestNamespace="urn:addin", ResponseNamespace="urn:addin")]
    [return: System.Xml.Serialization.SoapElementAttribute("getTitles2Return")]
    public StringsType getTitles2(AuthenticationType auth, string[] categoryTitles) {
        object[] results = this.Invoke("getTitles2", new object[] {
                    auth,
                    categoryTitles});
        return ((StringsType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetTitles2(AuthenticationType auth, string[] categoryTitles, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getTitles2", new object[] {
                    auth,
                    categoryTitles}, callback, asyncState);
    }
    
    /// <remarks/>
    public StringsType EndgetTitles2(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((StringsType)(results[0]));
    }
    
    /// <remarks/>
    public void getTitles2Async(AuthenticationType auth, string[] categoryTitles) {
        this.getTitles2Async(auth, categoryTitles, null);
    }
    
    /// <remarks/>
    public void getTitles2Async(AuthenticationType auth, string[] categoryTitles, object userState) {
        if ((this.getTitles2OperationCompleted == null)) {
            this.getTitles2OperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTitles2OperationCompleted);
        }
        this.InvokeAsync("getTitles2", new object[] {
                    auth,
                    categoryTitles}, this.getTitles2OperationCompleted, userState);
    }
    
    private void OngetTitles2OperationCompleted(object arg) {
        if ((this.getTitles2Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getTitles2Completed(this, new getTitles2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:addin/authenticate", RequestNamespace="urn:addin", ResponseNamespace="urn:addin")]
    [return: System.Xml.Serialization.SoapElementAttribute("authReturn")]
    public AuthReturnType authenticate(AuthenticationType auth) {
        object[] results = this.Invoke("authenticate", new object[] {
                    auth});
        return ((AuthReturnType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginauthenticate(AuthenticationType auth, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("authenticate", new object[] {
                    auth}, callback, asyncState);
    }
    
    /// <remarks/>
    public AuthReturnType Endauthenticate(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((AuthReturnType)(results[0]));
    }
    
    /// <remarks/>
    public void authenticateAsync(AuthenticationType auth) {
        this.authenticateAsync(auth, null);
    }
    
    /// <remarks/>
    public void authenticateAsync(AuthenticationType auth, object userState) {
        if ((this.authenticateOperationCompleted == null)) {
            this.authenticateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthenticateOperationCompleted);
        }
        this.InvokeAsync("authenticate", new object[] {
                    auth}, this.authenticateOperationCompleted, userState);
    }
    
    private void OnauthenticateOperationCompleted(object arg) {
        if ((this.authenticateCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.authenticateCompleted(this, new authenticateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:addin/saveNewMail2", RequestNamespace="urn:addin", ResponseNamespace="urn:addin")]
    [return: System.Xml.Serialization.SoapElementAttribute("saveNewMail2Return")]
    public ExceptionType saveNewMail2(AuthenticationType auth, string subject, string sender, string[] receivers, string[] ccs, System.DateTime sentDate, string basedMailPage, string action, string[] categories, string body, string[] attachments) {
        object[] results = this.Invoke("saveNewMail2", new object[] {
                    auth,
                    subject,
                    sender,
                    receivers,
                    ccs,
                    sentDate,
                    basedMailPage,
                    action,
                    categories,
                    body,
                    attachments});
        return ((ExceptionType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsaveNewMail2(AuthenticationType auth, string subject, string sender, string[] receivers, string[] ccs, System.DateTime sentDate, string basedMailPage, string action, string[] categories, string body, string[] attachments, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("saveNewMail2", new object[] {
                    auth,
                    subject,
                    sender,
                    receivers,
                    ccs,
                    sentDate,
                    basedMailPage,
                    action,
                    categories,
                    body,
                    attachments}, callback, asyncState);
    }
    
    /// <remarks/>
    public ExceptionType EndsaveNewMail2(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ExceptionType)(results[0]));
    }
    
    /// <remarks/>
    public void saveNewMail2Async(AuthenticationType auth, string subject, string sender, string[] receivers, string[] ccs, System.DateTime sentDate, string basedMailPage, string action, string[] categories, string body, string[] attachments) {
        this.saveNewMail2Async(auth, subject, sender, receivers, ccs, sentDate, basedMailPage, action, categories, body, attachments, null);
    }
    
    /// <remarks/>
    public void saveNewMail2Async(AuthenticationType auth, string subject, string sender, string[] receivers, string[] ccs, System.DateTime sentDate, string basedMailPage, string action, string[] categories, string body, string[] attachments, object userState) {
        if ((this.saveNewMail2OperationCompleted == null)) {
            this.saveNewMail2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveNewMail2OperationCompleted);
        }
        this.InvokeAsync("saveNewMail2", new object[] {
                    auth,
                    subject,
                    sender,
                    receivers,
                    ccs,
                    sentDate,
                    basedMailPage,
                    action,
                    categories,
                    body,
                    attachments}, this.saveNewMail2OperationCompleted, userState);
    }
    
    private void OnsaveNewMail2OperationCompleted(object arg) {
        if ((this.saveNewMail2Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.saveNewMail2Completed(this, new saveNewMail2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:addin/addCategory2", RequestNamespace="urn:addin", ResponseNamespace="urn:addin")]
    [return: System.Xml.Serialization.SoapElementAttribute("addCategory2Return")]
    public ExceptionType addCategory2(AuthenticationType auth, string categoryName) {
        object[] results = this.Invoke("addCategory2", new object[] {
                    auth,
                    categoryName});
        return ((ExceptionType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginaddCategory2(AuthenticationType auth, string categoryName, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("addCategory2", new object[] {
                    auth,
                    categoryName}, callback, asyncState);
    }
    
    /// <remarks/>
    public ExceptionType EndaddCategory2(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ExceptionType)(results[0]));
    }
    
    /// <remarks/>
    public void addCategory2Async(AuthenticationType auth, string categoryName) {
        this.addCategory2Async(auth, categoryName, null);
    }
    
    /// <remarks/>
    public void addCategory2Async(AuthenticationType auth, string categoryName, object userState) {
        if ((this.addCategory2OperationCompleted == null)) {
            this.addCategory2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddCategory2OperationCompleted);
        }
        this.InvokeAsync("addCategory2", new object[] {
                    auth,
                    categoryName}, this.addCategory2OperationCompleted, userState);
    }
    
    private void OnaddCategory2OperationCompleted(object arg) {
        if ((this.addCategory2Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.addCategory2Completed(this, new addCategory2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:addin/getPageInfo2", RequestNamespace="urn:addin", ResponseNamespace="urn:addin")]
    [return: System.Xml.Serialization.SoapElementAttribute("getPageInfo2Return")]
    public PageInfoType getPageInfo2(AuthenticationType auth, string title) {
        object[] results = this.Invoke("getPageInfo2", new object[] {
                    auth,
                    title});
        return ((PageInfoType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetPageInfo2(AuthenticationType auth, string title, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getPageInfo2", new object[] {
                    auth,
                    title}, callback, asyncState);
    }
    
    /// <remarks/>
    public PageInfoType EndgetPageInfo2(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((PageInfoType)(results[0]));
    }
    
    /// <remarks/>
    public void getPageInfo2Async(AuthenticationType auth, string title) {
        this.getPageInfo2Async(auth, title, null);
    }
    
    /// <remarks/>
    public void getPageInfo2Async(AuthenticationType auth, string title, object userState) {
        if ((this.getPageInfo2OperationCompleted == null)) {
            this.getPageInfo2OperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPageInfo2OperationCompleted);
        }
        this.InvokeAsync("getPageInfo2", new object[] {
                    auth,
                    title}, this.getPageInfo2OperationCompleted, userState);
    }
    
    private void OngetPageInfo2OperationCompleted(object arg) {
        if ((this.getPageInfo2Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getPageInfo2Completed(this, new getPageInfo2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:addin/getCategories2Detail", RequestNamespace="urn:addin", ResponseNamespace="urn:addin")]
    [return: System.Xml.Serialization.SoapElementAttribute("getCategories2DetailResponse")]
    public CommentsType getCategories2Detail(AuthenticationType auth) {
        object[] results = this.Invoke("getCategories2Detail", new object[] {
                    auth});
        return ((CommentsType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetCategories2Detail(AuthenticationType auth, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getCategories2Detail", new object[] {
                    auth}, callback, asyncState);
    }
    
    /// <remarks/>
    public CommentsType EndgetCategories2Detail(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CommentsType)(results[0]));
    }
    
    /// <remarks/>
    public void getCategories2DetailAsync(AuthenticationType auth) {
        this.getCategories2DetailAsync(auth, null);
    }
    
    /// <remarks/>
    public void getCategories2DetailAsync(AuthenticationType auth, object userState) {
        if ((this.getCategories2DetailOperationCompleted == null)) {
            this.getCategories2DetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCategories2DetailOperationCompleted);
        }
        this.InvokeAsync("getCategories2Detail", new object[] {
                    auth}, this.getCategories2DetailOperationCompleted, userState);
    }
    
    private void OngetCategories2DetailOperationCompleted(object arg) {
        if ((this.getCategories2DetailCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getCategories2DetailCompleted(this, new getCategories2DetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:addin/getPossibleForms", RequestNamespace="urn:addin", ResponseNamespace="urn:addin")]
    [return: System.Xml.Serialization.SoapElementAttribute("getPossibleFormsResponse")]
    public StringsType getPossibleForms(AuthenticationType auth, string form_name) {
        object[] results = this.Invoke("getPossibleForms", new object[] {
                    auth,
                    form_name});
        return ((StringsType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetPossibleForms(AuthenticationType auth, string form_name, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getPossibleForms", new object[] {
                    auth,
                    form_name}, callback, asyncState);
    }
    
    /// <remarks/>
    public StringsType EndgetPossibleForms(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((StringsType)(results[0]));
    }
    
    /// <remarks/>
    public void getPossibleFormsAsync(AuthenticationType auth, string form_name) {
        this.getPossibleFormsAsync(auth, form_name, null);
    }
    
    /// <remarks/>
    public void getPossibleFormsAsync(AuthenticationType auth, string form_name, object userState) {
        if ((this.getPossibleFormsOperationCompleted == null)) {
            this.getPossibleFormsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPossibleFormsOperationCompleted);
        }
        this.InvokeAsync("getPossibleForms", new object[] {
                    auth,
                    form_name}, this.getPossibleFormsOperationCompleted, userState);
    }
    
    private void OngetPossibleFormsOperationCompleted(object arg) {
        if ((this.getPossibleFormsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getPossibleFormsCompleted(this, new getPossibleFormsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:addin/savePageToForm", RequestNamespace="urn:addin", ResponseNamespace="urn:addin")]
    [return: System.Xml.Serialization.SoapElementAttribute("savePageToFormResponse")]
    public ExceptionType savePageToForm(AuthenticationType auth, string form_name, string page_name, PropertyPair[] properties, string freetext, string[] categories, string active_form, string[] applicable_forms) {
        object[] results = this.Invoke("savePageToForm", new object[] {
                    auth,
                    form_name,
                    page_name,
                    properties,
                    freetext,
                    categories,
                    active_form,
                    applicable_forms});
        return ((ExceptionType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsavePageToForm(AuthenticationType auth, string form_name, string page_name, PropertyPair[] properties, string freetext, string[] categories, string active_form, string[] applicable_forms, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("savePageToForm", new object[] {
                    auth,
                    form_name,
                    page_name,
                    properties,
                    freetext,
                    categories,
                    active_form,
                    applicable_forms}, callback, asyncState);
    }
    
    /// <remarks/>
    public ExceptionType EndsavePageToForm(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ExceptionType)(results[0]));
    }
    
    /// <remarks/>
    public void savePageToFormAsync(AuthenticationType auth, string form_name, string page_name, PropertyPair[] properties, string freetext, string[] categories, string active_form, string[] applicable_forms) {
        this.savePageToFormAsync(auth, form_name, page_name, properties, freetext, categories, active_form, applicable_forms, null);
    }
    
    /// <remarks/>
    public void savePageToFormAsync(AuthenticationType auth, string form_name, string page_name, PropertyPair[] properties, string freetext, string[] categories, string active_form, string[] applicable_forms, object userState) {
        if ((this.savePageToFormOperationCompleted == null)) {
            this.savePageToFormOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsavePageToFormOperationCompleted);
        }
        this.InvokeAsync("savePageToForm", new object[] {
                    auth,
                    form_name,
                    page_name,
                    properties,
                    freetext,
                    categories,
                    active_form,
                    applicable_forms}, this.savePageToFormOperationCompleted, userState);
    }
    
    private void OnsavePageToFormOperationCompleted(object arg) {
        if ((this.savePageToFormCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.savePageToFormCompleted(this, new savePageToFormCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:addin/createFormTemplate", RequestNamespace="urn:addin", ResponseNamespace="urn:addin")]
    [return: System.Xml.Serialization.SoapElementAttribute("createFormTemplateResponse")]
    public ExceptionType createFormTemplate(AuthenticationType auth, string name, PropertyPair[] properties) {
        object[] results = this.Invoke("createFormTemplate", new object[] {
                    auth,
                    name,
                    properties});
        return ((ExceptionType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincreateFormTemplate(AuthenticationType auth, string name, PropertyPair[] properties, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("createFormTemplate", new object[] {
                    auth,
                    name,
                    properties}, callback, asyncState);
    }
    
    /// <remarks/>
    public ExceptionType EndcreateFormTemplate(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ExceptionType)(results[0]));
    }
    
    /// <remarks/>
    public void createFormTemplateAsync(AuthenticationType auth, string name, PropertyPair[] properties) {
        this.createFormTemplateAsync(auth, name, properties, null);
    }
    
    /// <remarks/>
    public void createFormTemplateAsync(AuthenticationType auth, string name, PropertyPair[] properties, object userState) {
        if ((this.createFormTemplateOperationCompleted == null)) {
            this.createFormTemplateOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateFormTemplateOperationCompleted);
        }
        this.InvokeAsync("createFormTemplate", new object[] {
                    auth,
                    name,
                    properties}, this.createFormTemplateOperationCompleted, userState);
    }
    
    private void OncreateFormTemplateOperationCompleted(object arg) {
        if ((this.createFormTemplateCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.createFormTemplateCompleted(this, new createFormTemplateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:addin/savePageBasic", RequestNamespace="urn:addin", ResponseNamespace="urn:addin")]
    [return: System.Xml.Serialization.SoapElementAttribute("savePageBasicResponse")]
    public string savePageBasic(AuthenticationType auth, string form_name, string page_name, PropertyPair[] properties, string freetext) {
        object[] results = this.Invoke("savePageBasic", new object[] {
                    auth,
                    form_name,
                    page_name,
                    properties,
                    freetext});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsavePageBasic(AuthenticationType auth, string form_name, string page_name, PropertyPair[] properties, string freetext, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("savePageBasic", new object[] {
                    auth,
                    form_name,
                    page_name,
                    properties,
                    freetext}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndsavePageBasic(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void savePageBasicAsync(AuthenticationType auth, string form_name, string page_name, PropertyPair[] properties, string freetext) {
        this.savePageBasicAsync(auth, form_name, page_name, properties, freetext, null);
    }
    
    /// <remarks/>
    public void savePageBasicAsync(AuthenticationType auth, string form_name, string page_name, PropertyPair[] properties, string freetext, object userState) {
        if ((this.savePageBasicOperationCompleted == null)) {
            this.savePageBasicOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsavePageBasicOperationCompleted);
        }
        this.InvokeAsync("savePageBasic", new object[] {
                    auth,
                    form_name,
                    page_name,
                    properties,
                    freetext}, this.savePageBasicOperationCompleted, userState);
    }
    
    private void OnsavePageBasicOperationCompleted(object arg) {
        if ((this.savePageBasicCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.savePageBasicCompleted(this, new savePageBasicCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:addin/setPageForms", RequestNamespace="urn:addin", ResponseNamespace="urn:addin")]
    [return: System.Xml.Serialization.SoapElementAttribute("setPageFormsResponse")]
    public string setPageForms(AuthenticationType auth, string page_name, string active_form, string[] applicable_forms) {
        object[] results = this.Invoke("setPageForms", new object[] {
                    auth,
                    page_name,
                    active_form,
                    applicable_forms});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsetPageForms(AuthenticationType auth, string page_name, string active_form, string[] applicable_forms, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("setPageForms", new object[] {
                    auth,
                    page_name,
                    active_form,
                    applicable_forms}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndsetPageForms(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void setPageFormsAsync(AuthenticationType auth, string page_name, string active_form, string[] applicable_forms) {
        this.setPageFormsAsync(auth, page_name, active_form, applicable_forms, null);
    }
    
    /// <remarks/>
    public void setPageFormsAsync(AuthenticationType auth, string page_name, string active_form, string[] applicable_forms, object userState) {
        if ((this.setPageFormsOperationCompleted == null)) {
            this.setPageFormsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetPageFormsOperationCompleted);
        }
        this.InvokeAsync("setPageForms", new object[] {
                    auth,
                    page_name,
                    active_form,
                    applicable_forms}, this.setPageFormsOperationCompleted, userState);
    }
    
    private void OnsetPageFormsOperationCompleted(object arg) {
        if ((this.setPageFormsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.setPageFormsCompleted(this, new setPageFormsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:addin/getFormFieldValues", RequestNamespace="urn:addin", ResponseNamespace="urn:addin")]
    [return: System.Xml.Serialization.SoapElementAttribute("getFormFieldValuesResponse")]
    public PropertyPairsType getFormFieldValues(AuthenticationType auth, string title, string form_name) {
        object[] results = this.Invoke("getFormFieldValues", new object[] {
                    auth,
                    title,
                    form_name});
        return ((PropertyPairsType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetFormFieldValues(AuthenticationType auth, string title, string form_name, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getFormFieldValues", new object[] {
                    auth,
                    title,
                    form_name}, callback, asyncState);
    }
    
    /// <remarks/>
    public PropertyPairsType EndgetFormFieldValues(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((PropertyPairsType)(results[0]));
    }
    
    /// <remarks/>
    public void getFormFieldValuesAsync(AuthenticationType auth, string title, string form_name) {
        this.getFormFieldValuesAsync(auth, title, form_name, null);
    }
    
    /// <remarks/>
    public void getFormFieldValuesAsync(AuthenticationType auth, string title, string form_name, object userState) {
        if ((this.getFormFieldValuesOperationCompleted == null)) {
            this.getFormFieldValuesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFormFieldValuesOperationCompleted);
        }
        this.InvokeAsync("getFormFieldValues", new object[] {
                    auth,
                    title,
                    form_name}, this.getFormFieldValuesOperationCompleted, userState);
    }
    
    private void OngetFormFieldValuesOperationCompleted(object arg) {
        if ((this.getFormFieldValuesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getFormFieldValuesCompleted(this, new getFormFieldValuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:addin")]
public partial class PropertyPair {
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:addin")]
public partial class Comment {
    
    private string nameField;
    
    private string commentField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:addin")]
public partial class CommentsType {
    
    private ExceptionType exceptionField;
    
    private Comment[] valuesField;
    
    /// <remarks/>
    public ExceptionType exception {
        get {
            return this.exceptionField;
        }
        set {
            this.exceptionField = value;
        }
    }
    
    /// <remarks/>
    public Comment[] values {
        get {
            return this.valuesField;
        }
        set {
            this.valuesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:addin")]
public partial class ExceptionType {
    
    private string ret_codeField;
    
    private string messageField;
    
    /// <remarks/>
    public string ret_code {
        get {
            return this.ret_codeField;
        }
        set {
            this.ret_codeField = value;
        }
    }
    
    /// <remarks/>
    public string message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:addin")]
public partial class PageInfoType {
    
    private ExceptionType exceptionField;
    
    private PageInfo infoField;
    
    /// <remarks/>
    public ExceptionType exception {
        get {
            return this.exceptionField;
        }
        set {
            this.exceptionField = value;
        }
    }
    
    /// <remarks/>
    public PageInfo info {
        get {
            return this.infoField;
        }
        set {
            this.infoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:addin")]
public partial class PageInfo {
    
    private string authorField;
    
    private string lastUpdateField;
    
    private PropertyPair[] propertiesField;
    
    /// <remarks/>
    public string author {
        get {
            return this.authorField;
        }
        set {
            this.authorField = value;
        }
    }
    
    /// <remarks/>
    public string lastUpdate {
        get {
            return this.lastUpdateField;
        }
        set {
            this.lastUpdateField = value;
        }
    }
    
    /// <remarks/>
    public PropertyPair[] properties {
        get {
            return this.propertiesField;
        }
        set {
            this.propertiesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:addin")]
public partial class RestrictionType {
    
    private int restrictionField;
    
    private string[] supportedDomainsField;
    
    private string messageField;
    
    /// <remarks/>
    public int restriction {
        get {
            return this.restrictionField;
        }
        set {
            this.restrictionField = value;
        }
    }
    
    /// <remarks/>
    public string[] supportedDomains {
        get {
            return this.supportedDomainsField;
        }
        set {
            this.supportedDomainsField = value;
        }
    }
    
    /// <remarks/>
    public string message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:addin")]
public partial class AuthReturnType {
    
    private ExceptionType exceptionField;
    
    private RestrictionType restrictionField;
    
    /// <remarks/>
    public ExceptionType exception {
        get {
            return this.exceptionField;
        }
        set {
            this.exceptionField = value;
        }
    }
    
    /// <remarks/>
    public RestrictionType restriction {
        get {
            return this.restrictionField;
        }
        set {
            this.restrictionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:addin")]
public partial class PropertyPairsType {
    
    private ExceptionType exceptionField;
    
    private PropertyPair[] valuesField;
    
    /// <remarks/>
    public ExceptionType exception {
        get {
            return this.exceptionField;
        }
        set {
            this.exceptionField = value;
        }
    }
    
    /// <remarks/>
    public PropertyPair[] values {
        get {
            return this.valuesField;
        }
        set {
            this.valuesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:addin")]
public partial class StringsType {
    
    private ExceptionType exceptionField;
    
    private string[] valuesField;
    
    /// <remarks/>
    public ExceptionType exception {
        get {
            return this.exceptionField;
        }
        set {
            this.exceptionField = value;
        }
    }
    
    /// <remarks/>
    public string[] values {
        get {
            return this.valuesField;
        }
        set {
            this.valuesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:addin")]
public partial class AuthenticationType {
    
    private string userField;
    
    private string passwordField;
    
    private string typeField;
    
    private bool encryptedField;
    
    /// <remarks/>
    public string user {
        get {
            return this.userField;
        }
        set {
            this.userField = value;
        }
    }
    
    /// <remarks/>
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public bool encrypted {
        get {
            return this.encryptedField;
        }
        set {
            this.encryptedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:addin")]
public partial class ValidateType {
    
    private string nameField;
    
    private string versionField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void getCategoriesCompletedEventHandler(object sender, getCategoriesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void getPropertiesCompletedEventHandler(object sender, getPropertiesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getPropertiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getPropertiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void getTitlePropertiesCompletedEventHandler(object sender, getTitlePropertiesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getTitlePropertiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getTitlePropertiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public PropertyPair[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((PropertyPair[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void getTitlesCompletedEventHandler(object sender, getTitlesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getTitlesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getTitlesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void validateCompletedEventHandler(object sender, validateCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class validateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal validateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ValidateType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ValidateType)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void saveNewMailCompletedEventHandler(object sender, saveNewMailCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class saveNewMailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal saveNewMailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void addCategoryCompletedEventHandler(object sender, addCategoryCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class addCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal addCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void getPageInfoCompletedEventHandler(object sender, getPageInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getPageInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getPageInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public PageInfo Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((PageInfo)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void getCategories2CompletedEventHandler(object sender, getCategories2CompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getCategories2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getCategories2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public StringsType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((StringsType)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void getProperties2CompletedEventHandler(object sender, getProperties2CompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getProperties2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getProperties2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public StringsType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((StringsType)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void getTitleProperties2CompletedEventHandler(object sender, getTitleProperties2CompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getTitleProperties2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getTitleProperties2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public PropertyPairsType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((PropertyPairsType)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void getTitles2CompletedEventHandler(object sender, getTitles2CompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getTitles2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getTitles2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public StringsType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((StringsType)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void authenticateCompletedEventHandler(object sender, authenticateCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class authenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal authenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public AuthReturnType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((AuthReturnType)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void saveNewMail2CompletedEventHandler(object sender, saveNewMail2CompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class saveNewMail2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal saveNewMail2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ExceptionType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ExceptionType)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void addCategory2CompletedEventHandler(object sender, addCategory2CompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class addCategory2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal addCategory2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ExceptionType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ExceptionType)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void getPageInfo2CompletedEventHandler(object sender, getPageInfo2CompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getPageInfo2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getPageInfo2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public PageInfoType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((PageInfoType)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void getCategories2DetailCompletedEventHandler(object sender, getCategories2DetailCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getCategories2DetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getCategories2DetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CommentsType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CommentsType)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void getPossibleFormsCompletedEventHandler(object sender, getPossibleFormsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getPossibleFormsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getPossibleFormsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public StringsType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((StringsType)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void savePageToFormCompletedEventHandler(object sender, savePageToFormCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class savePageToFormCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal savePageToFormCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ExceptionType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ExceptionType)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void createFormTemplateCompletedEventHandler(object sender, createFormTemplateCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class createFormTemplateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal createFormTemplateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ExceptionType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ExceptionType)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void savePageBasicCompletedEventHandler(object sender, savePageBasicCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class savePageBasicCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal savePageBasicCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void setPageFormsCompletedEventHandler(object sender, setPageFormsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class setPageFormsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal setPageFormsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void getFormFieldValuesCompletedEventHandler(object sender, getFormFieldValuesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getFormFieldValuesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getFormFieldValuesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public PropertyPairsType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((PropertyPairsType)(this.results[0]));
        }
    }
}
