PageCRUDPlus: PCPClient Class Reference
PCPClient Class Reference
Inherits PCPAny.
Public Member Functions
PCPClient (PCPUserCredentials $useCredentials, PCPWikiSystem $wikiSystem)
login (PCPUserCredentials $userCredentials=NULL)
logout (PCPUserCredentials $userCredentials=NULL)
getEditToken (PCPUserCredentials $userCredentials=NULL, $title=NULL)
createPage (PCPUserCredentials $uc=NULL, $title=NULL, $text=NULL, $summary=NULL)
readPage (PCPUserCredentials $uc=NULL, $title=NULL, $revisionID=NULL)
updatePage (PCPUserCredentials $uc=NULL, $title=NULL, $text=NULL, $summary=NULL, $basetimestamp=NULL, $md5_hash=NULL)
deletePage (PCPUserCredentials $uc=NULL, $title=NULL, $reason=NULL)
movePage (PCPUserCredentials $uc=NULL, $fromTitle=NULL, $toTitle=NULL, $movetalk=false, $noredirect=false)
deleteCookies ()
__destruct ()
Public Attributes
$cookieFile = ''
Protected Attributes
$targetWiki
Private Attributes
$_returnFormat
Detailed Description
This is an abstract class used for creating API functions for the client side. NOT USED IN THE CURRENT VERSION.
Author:
Dian
Version:
0.1
Definition at line 9 of file Client.php.
Constructor & Destructor Documentation
PCPClient::__destruct ()
Definition at line 445 of file Client.php.
References cookieFile, and deleteCookies().
Member Function Documentation
PCPClient::createPage (PCPUserCredentials $ userCredentials = NULL, $ title = NULL, $ text = NULL, $ summary = NULL)
Create a page based on a title and return "true". If the page exists, "false" is returned.
Parameters:
PCPUserCredentials $userCredentials
String $title
String $text
String $summary
Returns:
boolean
Reimplemented from PCPAny.
Definition at line 151 of file Client.php.
References cookieFile, getEditToken(), login(), PCPUtil::replaceInHash(), and PCPUtil::trimFirstTitle().
PCPClient::deleteCookies ()
Definition at line 441 of file Client.php.
References cookieFile.
Referenced by __destruct().
PCPClient::deletePage (PCPUserCredentials $ uc = NULL, $ title = NULL, $ reason = NULL)
Definition at line 349 of file Client.php.
References cookieFile, getEditToken(), login(), PCPUtil::replaceInHash(), and PCPUtil::trimFirstTitle().
PCPClient::getEditToken (PCPUserCredentials $ userCredentials = NULL, $ title = NULL)
Get the cookies in a forms as described on the MediaWiki API pages.
Returns:
An array with cookies. Set the cookies after a successful login.
Parameters:
PCPUserCredentials $userCredentials Adds the cookies to the PCP object after a login.
PCPUserCredentials $userCredentials Get the edit token for a page.
PCPUserCredentials $userCredentials
string $title
Returns:
PCPUserCredentials The uc including the edit token.
Reimplemented from PCPAny.
Definition at line 93 of file Client.php.
References cookieFile, login(), PCPUtil::replaceInHash(), and PCPUtil::trimFirstTitle().
Referenced by createPage(), deletePage(), movePage(), and updatePage().
PCPClient::login (PCPUserCredentials $ userCredentials = NULL)
Login to a wiki system and save the connection data (cookies).
Parameters:
PCPUserCredentials $userCredentials
Returns:
PCPUserCredentials The uc after the login.
Reimplemented from PCPAny.
Definition at line 47 of file Client.php.
References cookieFile, and PCPUtil::replaceInHash().
Referenced by createPage(), deletePage(), getEditToken(), movePage(), readPage(), and updatePage().
PCPClient::logout (PCPUserCredentials $ userCredentials = NULL)
Logout from a wiki system and delete the connection data (cookies).
Parameters:
PCPUserCredentials $userCredentials
Reimplemented from PCPAny.
Definition at line 89 of file Client.php.
PCPClient::movePage (PCPUserCredentials $ userCredentials = NULL, $ fromTitle = NULL, $ toTitle = NULL, $ movetalk = false, $ noredirect = false)
Get the move token for a page.
Parameters:
string $title
Returns:
PCPUserCredentials The uc including the move token. Move a page in the wiki.
Parameters:
PCPUserCredentials $userCredentials
string $fromTitle
string $toTitle
boolean $movetalk
boolean $noredirect
Returns:
boolean
Reimplemented from PCPAny.
Definition at line 392 of file Client.php.
References cookieFile, getEditToken(), login(), and PCPUtil::replaceInHash().
PCPClient::PCPClient (PCPUserCredentials $ useCredentials, PCPWikiSystem $ wikiSystem)
The client constructor.
Parameters:
PCPUserCredentials $useCredentials The user credentials to be used.
PCPWikiSystem $wikiSystem The target wiki system.
Returns:
PCPClient
Definition at line 40 of file Client.php.
References cookieFile.
PCPClient::readPage (PCPUserCredentials $ userCredentials = NULL, $ title = NULL, $ revisionID = NULL)
Read a page from the wiki. If no revisionID given, read the latest revision. Redirects are NOT supported.
Parameters:
PCPUserCredentials $userCredentials
string $title
int $revisionID
Returns:
PCPPage
Reimplemented from PCPAny.
Definition at line 195 of file Client.php.
References cookieFile, login(), PCPUtil::replaceInHash(), and PCPUtil::trimFirstTitle().
PCPClient::updatePage (PCPUserCredentials $ userCredentials = NULL, $ title = NULL, $ text = NULL, $ summary = NULL, $ basetimestamp = NULL, $ md5_hash = NULL)
Update a page in the wiki. If the page doesn't exist, an error occurs. If the basetimestamp is not set, revision conflicts will be ignored. The md5 hash can be set to check if the text is corrupted.
Parameters:
PCPUserCredentials $userCredentials
string $title
string $text
string $summary
string $basetimestamp
string $md5_hash
Returns:
boolean
Reimplemented from PCPAny.
Definition at line 274 of file Client.php.
References cookieFile, getEditToken(), login(), PCPUtil::replaceInHash(), and PCPUtil::trimFirstTitle().
Member Data Documentation
PCPClient::$_returnFormat [private]
Definition at line 24 of file Client.php.
PCPClient::$cookieFile = ''
Definition at line 31 of file Client.php.
PCPClient::$targetWiki [protected]
Definition at line 16 of file Client.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/mw/extensions/PageCRUD_Plus/PCP/Client.php