PageCRUDPlus: PCPUtil Class Reference
PCPUtil Class Reference
Static Public Member Functions
static replaceInHash ($placeholders=NULL, $values=NULL)
static fromURL ($string)
static toURL ($string)
static trimFirstTitle ($title=NULL)
static createXMLResponse ($result, $status="success")
static array2Object ($array)
static object2Array ($object)
Detailed Description
PCP utilities.
Author:
Dian
Version:
0.1
Definition at line 8 of file Util.php.
Member Function Documentation
static PCPUtil::array2Object ($ array) [static]
Converts an array into an obect (from a nonspecific type).
Parameters:
array $array
Returns:
obejct The converted array.
Definition at line 116 of file Util.php.
static PCPUtil::createXMLResponse ($ result, $ status = "success") [static]
Create a response for the REST server. Passed results have two types of elements:
*page-Element or *userCredentials -Element.
Example:
<response> <smw> <page> <!--here comes the page data--> </page> <userCredetials un="Tester" pw="test" .../> </smw> </response>
See also:
PCPUserCredentials
PCPPage
Parameters:
string $result The result of a function call - an XML element.
string $status The status of the operation: success or failed.
Returns:
string The XML string.
Definition at line 100 of file Util.php.
References $result.
Referenced by createPage(), and readPage().
static PCPUtil::fromURL ($ string) [static]
Public. Convert a string from URL-format to UTF8 proper.
Parameters:
string $string the name of the article, urlencoded
Returns:
string the UTF8 name of the same article
Definition at line 37 of file Util.php.
static PCPUtil::object2Array ($ object) [static]
Converts an object into a hashmap (array).
Parameters:
object $object
Returns:
array The converted object.
Definition at line 135 of file Util.php.
static PCPUtil::replaceInHash ($ placeholders = NULL, $ values = NULL) [static]
Replaces placeholders with the given values.
Parameters:
string[] $placeholders The placeholders have the form ':n' with 'n' a digit.
string[] $values The values.
Returns:
strung[] The replacements.
Definition at line 16 of file Util.php.
Referenced by PCPServer::createPage(), PCPClient::createPage(), PCPServer::deletePage(), PCPClient::deletePage(), PCPServer::getEditToken(), PCPClient::getEditToken(), PCPServer::login(), PCPClient::login(), PCPServer::movePage(), PCPClient::movePage(), PCPServer::readPage(), PCPClient::readPage(), PCPServer::updatePage(), and PCPClient::updatePage().
static PCPUtil::toURL ($ string) [static]
Public. Convert a string from UTF8 to URL format
Parameters:
string $string the UTF8 name of the article
Returns:
string the name of the same article, urlencoded
Definition at line 49 of file Util.php.
static PCPUtil::trimFirstTitle ($ title = NULL) [static]
If the title sting contains more than one title, return only the first one. The titles are supposed to be separated by a '|'.
Parameters:
string $title
Returns:
string The single title.
Definition at line 68 of file Util.php.
Referenced by PCPClient::createPage(), PCPClient::deletePage(), PCPServer::getEditToken(), PCPClient::getEditToken(), PCPServer::readPage(), PCPClient::readPage(), and PCPClient::updatePage().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/mw/extensions/PageCRUD_Plus/Util/Util.php