PageObjectModel(POM): DLList Class Reference
DLList Class Reference
Public Member Functions
DLList ()
addAtPosition ($index, &$object)
insertNodeInList (&$newNode, &$nodeAtIndex)
add (&$object)
getNewNode (&$object)
clear ()
get ($index)
isEmpty ()
removeAtIndex ($index)
remove ($element)
& getNode ($index)
& getNodeReversed ($index)
size ()
listIterator ()
setShortcutTypes ($types)
& getShortcuts ($type=NULL)
shortcutsListIterator ($type)
getPosition (POMElement $element)
Public Attributes
$head
$tail
$size
Private Member Functions
incSize ()
decSize ()
addShortcut (&$object)
removeShortcut (&$object)
Private Attributes
$shortcuts = NULL
Detailed Description
The class represents a double linked list specially suited for adding POM elements.
Definition at line 6 of file UtilData.php.
Member Function Documentation
DLList::add (&$ object)
Create a new node, Appends a new node to the tail
Parameters:
&$object The element you want to append to the list.
Returns:
boolean True if successful and false if not.
Definition at line 94 of file UtilData.php.
References addShortcut(), getNewNode(), isEmpty(), and size().
DLList::addAtPosition ($ index, &$ object)
Adds a new object at a specific index, pushes the current further back into the list.
Parameters:
$index Numeric value between 0 and $this->size()-1
&$object A reference to the object that is to be inserted
Returns:
TRUE == insertino ok || FALSE == index out of bounds
Definition at line 41 of file UtilData.php.
References addShortcut(), getNewNode(), getNode(), insertNodeInList(), and size().
DLList::addShortcut (&$ object) [private]
Definition at line 348 of file UtilData.php.
Referenced by add(), and addAtPosition().
DLList::clear ()
Empties the list.
Definition at line 128 of file UtilData.php.
References size().
DLList::decSize () [private]
Definition at line 316 of file UtilData.php.
References size().
DLList::DLList ()
Class constructor.
Returns:
DLList
Definition at line 23 of file UtilData.php.
References size().
Referenced by setShortcutTypes().
DLList::get ($ index)
Retrevies the object at the specified index.
Parameters:
$index A value between 0 and $this->size()
Returns:
The object || FALSE == index out of bounds
Definition at line 139 of file UtilData.php.
References getNode(), getNodeReversed(), isEmpty(), and size().
DLList::getNewNode (&$ object)
Generates a new ListNode object.
Parameters:
&$object The value of the ListNode
Returns:
A ListNode object
Definition at line 121 of file UtilData.php.
Referenced by add(), and addAtPosition().
& DLList::getNode ($ index)
Retrevies a node at a spesific index
Parameters:
$index A value between 0 and $this->size()
Returns:
The node || FALSE == index out of bounds
Definition at line 255 of file UtilData.php.
References isEmpty(), and size().
Referenced by addAtPosition(), get(), and removeAtIndex().
& DLList::getNodeReversed ($ index)
Retrevies the object from the tail of the list
Parameters:
$index A value between 0 and $this->size()
Returns:
The node || FALSE == index out of bounds
Definition at line 272 of file UtilData.php.
References isEmpty(), and size().
Referenced by get().
DLList::getPosition (POMElement $ element)
Get the position in the list of a specific element.
Parameters:
POMElement $element The elemnt for which the position will be determined.
Returns:
int The position in the list.
Definition at line 390 of file UtilData.php.
References isEmpty(), and size().
& DLList::getShortcuts ($ type = NULL)
Gets specific elements of the page.
Parameters:
string $type The requested element type. If set, return this specific type of elements. If not, return all elements.
Returns:
DLList A list of elements.
Definition at line 340 of file UtilData.php.
DLList::incSize () [private]
Definition at line 312 of file UtilData.php.
References size().
DLList::insertNodeInList (&$ newNode, &$ nodeAtIndex)
Inserts a new node into a the list on a position where it has nodes bothe before an after. NOT at index 0 or $this->size()-1
Parameters:
&$newNode A reference to the node that is inserted in the list.
&$nodeAtIndex The node it is pushing away.
Definition at line 78 of file UtilData.php.
Referenced by addAtPosition().
DLList::isEmpty ()
Checks if the list is empty
Returns:
TRUE == empty || FALSE == not empty
Definition at line 158 of file UtilData.php.
References size().
Referenced by add(), get(), getNode(), getNodeReversed(), getPosition(), remove(), and removeAtIndex().
DLList::listIterator ()
Returns an iterator to use on the list
Returns:
An Iterator object, tha iterator starts on the list head. Returns an ListIterator to use on the list
An ListIterator object, tha iterator starts on the list head.
Definition at line 307 of file UtilData.php.
DLList::remove ($ element)
Removes the given element from the elements in the list.
Parameters:
POMElement $element
Returns:
boolean True if successful and false else.
Definition at line 215 of file UtilData.php.
References isEmpty(), removeShortcut(), and size().
DLList::removeAtIndex ($ index)
Removes a node from the liste at the given index
Parameters:
int $index The position of the node in the list.
Returns:
unknown
Definition at line 168 of file UtilData.php.
References getNode(), isEmpty(), removeShortcut(), and size().
DLList::removeShortcut (&$ object) [private]
Definition at line 358 of file UtilData.php.
Referenced by remove(), and removeAtIndex().
DLList::setShortcutTypes ($ types)
Sets what types of elements will be added to the shortcut list.
Parameters:
unknown_type $types
Definition at line 327 of file UtilData.php.
References DLList().
DLList::shortcutsListIterator ($ type)
Returns an DLListIterator to use on the list
Parameters:
string $type The type of the objects for which the shortcuts are iterated.
Returns:
An DLListIterator object, tha iterator starts on the list head. Iterates through the specific types of elements on a page.
Parameters:
string $type The requested type of elements.
Returns:
DLListIterator The iterator over the element nodes.
Definition at line 379 of file UtilData.php.
DLList::size ()
Returns the size of the list
Returns:
The number of elements in the list
Definition at line 290 of file UtilData.php.
Referenced by add(), addAtPosition(), clear(), decSize(), DLList(), get(), getNode(), getNodeReversed(), getPosition(), incSize(), isEmpty(), remove(), and removeAtIndex().
Member Data Documentation
DLList::$head
Definition at line 7 of file UtilData.php.
DLList::$shortcuts = NULL [private]
Definition at line 16 of file UtilData.php.
DLList::$size
Definition at line 9 of file UtilData.php.
DLList::$tail
Definition at line 8 of file UtilData.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/mw/extensions/PageObjectModel/Util/UtilData.php