PageCRUDPlus: F:/xampp/htdocs/mw/extensions/DataAPI/PageObjectModel/Examples/ExampleTemplateAndPCP.php File Reference
F:/xampp/htdocs/mw/extensions/DataAPI/PageObjectModel/Examples/ExampleTemplateAndPCP.php File Reference
Variables
$__smwSystem = new PCPWikiSystem("http://localhost/smw")
$__userCredentials
$__client = new PCPClient($__userCredentials, $__smwSystem)
$__page
$__pom
$__iterator = $__pom->getTemplateByTitle("Testtemplate")->listIterator()
$__template = &$__iterator->getNextNodeValueByReference()
Variable Documentation
$__client = new PCPClient($__userCredentials, $__smwSystem)
Definition at line 20 of file ExampleTemplateAndPCP.php.
$__iterator = $__pom->getTemplateByTitle("Testtemplate")->listIterator()
Definition at line 38 of file ExampleTemplateAndPCP.php.
Referenced by POMPage::delete(), POMPage::getCategoryByID(), POMPage::getCategoryByName(), POMPage::getElement(), POMPage::getPropertyByID(), POMPage::getPropertyByName(), POMPage::getSimpleText(), POMPage::getTemplateByID(), POMPage::getTemplateByTitle(), POMPage::sync(), and POMPage::update().
$__page
Initial value:
 $__client->readPage(
                $__userCredentials,
                "testpage")
Definition at line 27 of file ExampleTemplateAndPCP.php.
$__pom
Initial value:
 new POMPage(
                $__page->title,
                $__page->text
                )
Definition at line 32 of file ExampleTemplateAndPCP.php.
Referenced by POMPageWS_API::getCategories(), POMPageWS_API::getCategoryByName(), POMPageWS_API::getElements(), POMPageWS_API::getProperties(), POMPageWS_API::getPropertyByName(), POMPageWS_API::getSimpleTexts(), POMPageWS_API::getTemplateByTitle(), POMPageWS_API::getTemplates(), and POMPageWS_API::toArray().
$__smwSystem = new PCPWikiSystem("http://localhost/smw")
This example presumes that POM is used directly on the client-side. The POM and PCP extensions must be installed properly on both client- and server-side.
Definition at line 11 of file ExampleTemplateAndPCP.php.
$__template = &$__iterator->getNextNodeValueByReference()
Definition at line 41 of file ExampleTemplateAndPCP.php.
$__userCredentials
Initial value:
 new PCPUserCredentials(
                "user", # the username
                "pass" # the password
                )
Definition at line 14 of file ExampleTemplateAndPCP.php.
Referenced by POMPageWS_API::getCategories(), POMPageWS_API::getCategoryByName(), POMPageWS_API::getElements(), POMPageWS_API::getProperties(), POMPageWS_API::getPropertyByName(), POMPageWS_API::getSimpleTexts(), POMPageWS_API::getTemplateByTitle(), and POMPageWS_API::getTemplates().