PageCRUDPlus: C:/xampp/htdocs/mw/extensions/PageCRUD_Plus/Test/TestLogin.php File Reference
C:/xampp/htdocs/mw/extensions/PageCRUD_Plus/Test/TestLogin.php File Reference
Variables
$uc = new PCPUserCredentials("WikiSysop", "!>ontoprise?")
$ws = new PCPWikiSystem("http://localhost/mw")
$loginTest = new PCPClient($uc,$ws)
$loginTest cookieFile = getcwd()."/cookiejar.txt"
Variable Documentation
$loginTest = new PCPClient($uc,$ws)
Definition at line 8 of file TestLogin.php.
$uc = new PCPUserCredentials("WikiSysop", "!>ontoprise?")
Definition at line 6 of file TestLogin.php.
$ws = new PCPWikiSystem("http://localhost/mw")
Definition at line 7 of file TestLogin.php.
$loginTest cookieFile = getcwd()."/cookiejar.txt"
Definition at line 9 of file TestLogin.php.
Referenced by PCPClient::__destruct(), PCPClient::createPage(), PCPClient::deleteCookies(), PCPClient::deletePage(), PCPClient::getEditToken(), PCPClient::login(), PCPClient::movePage(), PCPClient::PCPClient(), PCPClient::readPage(), and PCPClient::updatePage().