PageCRUDPlus: PCPServerWS_API Class Reference
PCPServerWS_API Class Reference
Public Member Functions
__construct ($query, $moduleName)
execute ()
getVersion ()
Protected Member Functions
getAllowedParams ()
getParamDescription ()
getDescription ()
getExamples ()
createPage ($username=NULL, $password=NULL, $id=NULL, $loginToken=NULL, $editToken=NULL, $title=NULL, $text=NULL, $summary=NULL)
readPage ($username=NULL, $password=NULL, $id=NULL, $loginToken=NULL, $editToken=NULL, $title=NULL, $revisionID=NULL)
updatePage ($username=NULL, $password=NULL, $id=NULL, $loginToken=NULL, $editToken=NULL, $title=NULL, $text=NULL, $summary=NULL, $basetimestamp=NULL, $md5_hash=NULL)
deletePage ($username=NULL, $password=NULL, $id=NULL, $loginToken=NULL, $editToken=NULL, $title=NULL)
movePage ($username=NULL, $password=NULL, $id=NULL, $loginToken=NULL, $editToken=NULL, $fromTitle=NULL, $toTitle=NULL, $movetalk=false, $noredirect=false)
Detailed Description
Definition at line 19 of file ServerAPI.php.
Constructor & Destructor Documentation
PCPServerWS_API::__construct ($ query, $ moduleName)
Definition at line 21 of file ServerAPI.php.
Member Function Documentation
PCPServerWS_API::createPage ($ username = NULL, $ password = NULL, $ id = NULL, $ loginToken = NULL, $ editToken = NULL, $ title = NULL, $ text = NULL, $ summary = NULL) [protected]
Create a new page.
Parameters:
string $username
string $password
string $id
string $loginToken
string $editToken
string $title
string $text
string $summary
Returns:
status
Definition at line 215 of file ServerAPI.php.
Referenced by execute().
PCPServerWS_API::deletePage ($ username = NULL, $ password = NULL, $ id = NULL, $ loginToken = NULL, $ editToken = NULL, $ title = NULL) [protected]
Delete a page.
Parameters:
string $username
string $password
string $id
string $loginToken
string $editToken
string $title
Returns:
status
Definition at line 274 of file ServerAPI.php.
Referenced by execute().
PCPServerWS_API::execute ()
Definition at line 25 of file ServerAPI.php.
References $result, createPage(), deletePage(), movePage(), readPage(), and updatePage().
PCPServerWS_API::getAllowedParams () [protected]
Definition at line 138 of file ServerAPI.php.
PCPServerWS_API::getDescription () [protected]
Definition at line 188 of file ServerAPI.php.
PCPServerWS_API::getExamples () [protected]
Definition at line 192 of file ServerAPI.php.
PCPServerWS_API::getParamDescription () [protected]
Definition at line 166 of file ServerAPI.php.
PCPServerWS_API::getVersion ()
Definition at line 199 of file ServerAPI.php.
PCPServerWS_API::movePage ($ username = NULL, $ password = NULL, $ id = NULL, $ loginToken = NULL, $ editToken = NULL, $ fromTitle = NULL, $ toTitle = NULL, $ movetalk = false, $ noredirect = false) [protected]
Move a page.
Parameters:
string $username
string $password
string $id
string $loginToken
string $editToken
string $fromTitle
string $toTitle
string $movetalk
string $noredirect
Returns:
status
Definition at line 295 of file ServerAPI.php.
Referenced by execute().
PCPServerWS_API::readPage ($ username = NULL, $ password = NULL, $ id = NULL, $ loginToken = NULL, $ editToken = NULL, $ title = NULL, $ revisionID = NULL) [protected]
Read a page.
Parameters:
string $username
string $password
string $id
string $loginToken
string $editToken
string $title
string $revisionID
Returns:
PCPPage The page.
Definition at line 234 of file ServerAPI.php.
Referenced by execute().
PCPServerWS_API::updatePage ($ username = NULL, $ password = NULL, $ id = NULL, $ loginToken = NULL, $ editToken = NULL, $ title = NULL, $ text = NULL, $ summary = NULL, $ basetimestamp = NULL, $ md5_hash = NULL) [protected]
Update a page.
Parameters:
string $username
string $password
string $id
string $loginToken
string $editToken
string $title
string $text
string $summary
string $basetimestamp
string $md5_hash
Returns:
status
Definition at line 256 of file ServerAPI.php.
Referenced by execute().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/mw/extensions/PageCRUD_Plus/WS/ServerAPI.php