PageCRUDPlus: POMProperty Class Reference
POMProperty Class Reference
Inherits POMAnnotation.
Public Member Functions
POMProperty ($text)
toString ()
getName ()
setName ($name)
getValue ()
setValue ($value)
getRepresentation ()
setRepresentation ($representation)
Static Public Member Functions
static createProperty ($name, $value, $representation=NULL)
Private Member Functions
parseName ($text)
parseValue ($text)
parseRepresentation ($text)
Detailed Description
The property class.
PLEASE NOTE: n-ary properties are generally not supported since the value in a name::value pair is represented as a string and DOESN'T underly further processing, e.g. splitting by ';' or checking the property type on the property definition page.
Definition at line 117 of file Annotation.php.
Member Function Documentation
static POMProperty::createProperty ($ name, $ value, $ representation = NULL) [static]
Class constructor. Creates the annotation based on the given parameters.
Parameters:
string $name
string $value
string $representation
Returns:
POMProperty
Definition at line 145 of file Annotation.php.
References POMAnnotation::$representation, POMAnnotation::$value, and POMProperty().
POMProperty::getName ()
Get the name of the property.
Returns:
string The name of the property.
Definition at line 207 of file Annotation.php.
POMProperty::getRepresentation ()
Get the representation of the property.
Returns:
string The representation of the property.
Definition at line 243 of file Annotation.php.
POMProperty::getValue ()
Get the value of the property.
Returns:
string The value of the property.
Definition at line 225 of file Annotation.php.
POMProperty::parseName ($ text) [private]
Definition at line 172 of file Annotation.php.
Referenced by POMProperty().
POMProperty::parseRepresentation ($ text) [private]
Definition at line 192 of file Annotation.php.
Referenced by POMProperty().
POMProperty::parseValue ($ text) [private]
Definition at line 180 of file Annotation.php.
Referenced by POMProperty().
POMProperty::POMProperty ($ text)
Class constructor. Parses all annotation attributes.
Parameters:
string $text The original text.
Returns:
POMAnnotation
Definition at line 124 of file Annotation.php.
References POMElement::$elementCounter, parseName(), parseRepresentation(), and parseValue().
Referenced by createProperty().
POMProperty::setName ($ name)
Set the name of the property.
Parameters:
string $name The name.
Definition at line 216 of file Annotation.php.
References POMAnnotation::$name.
POMProperty::setRepresentation ($ representation)
Set the representation of the property.
Parameters:
string $representation The representation.
Definition at line 252 of file Annotation.php.
References POMAnnotation::$representation.
POMProperty::setValue ($ value)
Set the value of the property.
Parameters:
string $value The value.
Definition at line 234 of file Annotation.php.
References POMAnnotation::$value.
POMProperty::toString ()
Copies the current attribute values into a string representing a property annotation.
Returns:
string The markup for the property.
Reimplemented from POMElement.
Definition at line 161 of file Annotation.php.
The documentation for this class was generated from the following file:
F:/xampp/htdocs/mw/extensions/DataAPI/PageObjectModel/POM/Annotation.php