PageCRUDPlus: POMCategory Class Reference
POMCategory Class Reference
Inherits POMAnnotation.
Public Member Functions
POMCategory ($text)
toString ()
getValue ()
setValue ($value)
Static Public Member Functions
static createCategory ($value)
Private Member Functions
parseValue ($text)
Detailed Description
The category class used.
Definition at line 35 of file Annotation.php.
Member Function Documentation
static POMCategory::createCategory ($ value) [static]
Class constructor. Creates the annotation based on the given parameters.
Parameters:
string $value The name of the category.
Returns:
POMCategory
Definition at line 61 of file Annotation.php.
References POMCategory().
POMCategory::getValue ()
Get the value of the category.
Returns:
string The value of the category.
Definition at line 96 of file Annotation.php.
POMCategory::parseValue ($ text) [private]
Definition at line 67 of file Annotation.php.
Referenced by POMCategory().
POMCategory::POMCategory ($ text)
Class constructor. Parses all category attributes.
Parameters:
string $text The original text.
Returns:
POMAnnotation
Definition at line 42 of file Annotation.php.
References POMElement::$elementCounter, and parseValue().
Referenced by createCategory().
POMCategory::setValue ($ value)
Set the value of the category.
Parameters:
string $value The value.
Definition at line 105 of file Annotation.php.
References POMAnnotation::$value.
POMCategory::toString ()
Copies the current attribute values into a string representing a category annotation.
Returns:
string The markup for the category.
Reimplemented from POMElement.
Definition at line 84 of file Annotation.php.
The documentation for this class was generated from the following file:
F:/xampp/htdocs/mw/extensions/DataAPI/PageObjectModel/POM/Annotation.php