PageCRUDPlus: POMPage Class Reference
POMPage Class Reference
Public Member Functions
POMPage ($title, $text, $parsers=array('POMExtendedParser'))
getNamespace ()
addElement (POMElement &$element)
addElementAtPosition (POMElement &$element, $position=-1)
addElementBefore (POMElement &$oldElement, POMElement &$newElement)
addElementAfter (POMElement $oldElement, POMElement &$newElement)
& getElement ($id=NULL)
& getElements ()
& getTemplates ($type= 'POMTemplate')
& getTemplateByID ($id=NULL, $type= 'POMTemplate')
& getTemplateByTitle ($title= '', $type= 'POMTemplate')
& getProperties ()
& getPropertyByID ($id=NULL)
& getPropertyByName ($name= '')
& getCategories ()
& getCategoryByID ($id=NULL)
& getCategoryByName ($name= '')
& getSimpleTexts ()
& getSimpleText ($id=NULL)
sync ()
searchInTextAtPosition ($textPos=-1)
& update (POMElement $element=NULL)
& delete (POMElement $element=NULL)
toString ()
Static Public Member Functions
static fromPCPPage (PCPPage $pcpPageObj=NULL, $parsers=array('POMExtendedParser'))
Protected Attributes
$children
Detailed Description
Page class reprersents a wiki page. The wiki page consists of elements, which In order to create a page, the page title and text are needed. The text must be the row wiki mark-up. can again have page objects as children. For example, a template parameter could have a template as value. More text parsers could be used, but at this version only the POMExtendedParser is supported. Let's take a look of the following example showing the usage of the POMPage class:
Suppose the the following example page in your wiki named 'Testpage' (shown in wiki mark-up):
{{TemplateName
|Created at=a couple of days ago
|anotherParameter=another value
}}
And here comes text ...
Now let's use the following test code:
// step 1
$pom = new POMPage('Testpage', join(file('http://<wikihome>/index.php?title=Testpage&action=raw')));
// step 2
$iterator = $pom->getTemplateByTitle("TemplateName")->listIterator();
while($iterator->hasNext()){
// step 3
$template = &$iterator->getNextNodeValueByReference();
// step 4
if ($template->getParameter("Created at") !== NULL){
// step 5
$simpleText = &$template->getParameter("Created at")->getValueByReference()->getSimpleText();
$simpleText = new POMSimpleText("today");
}
}
The steps do the following:
1. One can use the PCPPage and the PageCRUD_Plus package to read the content of a page, but we will use a simple way to access the wiki mark-up in order to concentrate on the actual example.
2. Create an iterator over the templates named 'TemplateName' of the 'Testpage'.
3. For each template in the retrieved list, get a direct reference (access only by value is supported too).
4. Check if a parameter 'Created at' exits.
5. Get a reference to the parameter value and set the new value to a new simple text element ("today").
The object based structure of the page looks like:
page 'Testpage'
-> child template 'TemplateName'
-> child template parameter 'Created at'
-> child page 'temporarypage' (a programmer doesn't see this object directly)
-> child simple text 'today'
The expected result is:
{{TemplateName
|Created at=today
|anotherParameter=another value
}}
And here comes text ...
See also:
PCPPage
POMElement
Author:
Sergey Chernyshev
Dian As of version 0.4.
Definition at line 78 of file Page.php.
Member Function Documentation
POMPage::addElement (POMElement &$ element)
Add an element to the tail of the children list of the page.
See also:
addElementAtPosition
Parameters:
POMElement $element
Definition at line 170 of file Page.php.
References addElementAtPosition().
Referenced by POMExtendedParser::Parse().
POMPage::addElementAfter (POMElement $ oldElement, POMElement &$ newElement)
Adds teh new element after the given element which already exists in the child list of the page.
Parameters:
POMElement $oldElement The referenced element in the child list.
POMElement $newElement The element to be added.
Returns:
TRUE == insertin ok || FALSE == error adding element
Definition at line 284 of file Page.php.
POMPage::addElementAtPosition (POMElement &$ element, $ position = -1)
Add a an element to the page. The element is added at the specific position in the text. There are several cases covered - the requested position is within:
a template => no child is added, but an error is returned.
an annotation => there are two subcases - the object to be added is:
-- an annotation => no child is added, the new annotation replaces the old annotation.
-- not an annotation => no changes applied.
a simple text => there are two subcases - the object to be added is:
-- also a simple text => the text is added at the requirede position - only the node text is retrieved, the ID is ignored.
-- not a simple text => the old object is splitted into two new objects with the new object in between.
Parameters:
POMElement $node The child element to be added.
int $position The position in the text, at which the child must be added. If not set, adds the child at the end of the page.
Returns:
True, if operation successful or false, if an error occured.
Definition at line 190 of file Page.php.
References searchInTextAtPosition().
Referenced by addElement().
POMPage::addElementBefore (POMElement &$ oldElement, POMElement &$ newElement)
Adds the new element before the given element which already exists in the child list of the page.
Parameters:
POMElement $oldElement The referenced element in the child list.
POMElement $newElement The element to be added.
Returns:
TRUE == insertin ok || FALSE == error adding element
Definition at line 272 of file Page.php.
& POMPage::delete (POMElement $ element = NULL)
Deletes a given element on the page. The element is identified by it's ID.
Parameters:
POMElement $element
Returns:
boolean True if successful, false if not.
Definition at line 590 of file Page.php.
References $__iterator.
static POMPage::fromPCPPage (PCPPage $ pcpPageObj = NULL, $ parsers = array('POMExtendedParser')) [static]
Definition at line 125 of file Page.php.
References POMPage().
& POMPage::getCategories ()
Retrieve all categories on a page.
Returns:
DLList The categories.
Definition at line 440 of file Page.php.
& POMPage::getCategoryByID ($ id = NULL)
Retrieve a specific category based on the ID. If no ID is given, the first category is returned.
Parameters:
string $id The ID of the element.
Returns:
POMCategory The category found or NULL.
Definition at line 452 of file Page.php.
References $__iterator.
& POMPage::getCategoryByName ($ name = '')
Retrieve a specific category based on the name. If no name is given, the first category is returned.
Parameters:
string $name The name of the element.
Returns:
DLList(POMProperty) The category(ies) found or empty list.
Definition at line 475 of file Page.php.
References $__iterator.
& POMPage::getElement ($ id = NULL)
Definition at line 294 of file Page.php.
References $__iterator.
& POMPage::getElements ()
Definition at line 313 of file Page.php.
POMPage::getNamespace ()
Get the namespace of the page.
Returns:
string
Definition at line 160 of file Page.php.
& POMPage::getProperties ()
Retrieve all properties on a page.
Returns:
DLList The properties.
Definition at line 384 of file Page.php.
& POMPage::getPropertyByID ($ id = NULL)
Retrieve a specific property based on the ID. If no ID is given, the first property is returned.
Parameters:
string $id The ID of the element.
Returns:
POMProperty The property found or NULL.
Definition at line 396 of file Page.php.
References $__iterator.
& POMPage::getPropertyByName ($ name = '')
Retrieve a specific property based on the name. If no name is given, the first property is returned.
Parameters:
string $name The name of the element.
Returns:
DLList(POMProperty) The property(ies) found or empty list.
Definition at line 419 of file Page.php.
References $__iterator.
& POMPage::getSimpleText ($ id = NULL)
Retrieve a specific simple text based on the ID. If no ID is given, the first simple text is returned.
Parameters:
string $id The ID of the element.
Returns:
<POMSimpleText> The simple text found or NULL.
Definition at line 509 of file Page.php.
References $__iterator.
& POMPage::getSimpleTexts ()
Retrieve all simple texts on a page.
Returns:
DLList The simple texts.
Definition at line 497 of file Page.php.
& POMPage::getTemplateByID ($ id = NULL, $ type = 'POMTemplate')
Retrieve a specific template based on the ID. If no ID is given, the first template is returned.
Parameters:
string $id The ID of the element.
string $type The type of the template. Possible values are any of the template class hierarchy names. Multiple values are separated by '|'.
See also:
POMTemplate
Returns:
POMTemplate The template found or NULL.
Definition at line 338 of file Page.php.
References $__iterator.
& POMPage::getTemplateByTitle ($ title = '', $ type = 'POMTemplate')
Retrieve a specific template based on the title. If no title is given, the first template is returned.
Parameters:
string $title The ID of the element.
string $type The type of the template. Possible values are any of the template class hierarchy names. Multiple values are separated by '|'.
See also:
POMTemplate
Returns:
DLList(POMTemplate) The template(s) found or an empty list.
Definition at line 362 of file Page.php.
References $__iterator.
& POMPage::getTemplates ($ type = 'POMTemplate')
Retrieve all templates on a page.
Parameters:
string $type The type of the template. Possible values are any of the template class hierarchy names. Multiple values are separated by '|'.
See also:
POMTemplate
Returns:
DLList The templates.
Definition at line 325 of file Page.php.
POMPage::POMPage ($ title, $ text, $ parsers = array('POMExtendedParser'))
The constructor of the class. In the constructor the supported element types are set. If an element is added and it is not in the list of the supported elemens, a "Object of class DLList could not be converted to string " exception is thrown.
Parameters:
string $title
string $text
string[] $parsers
Returns:
POMPage
Definition at line 96 of file Page.php.
Referenced by fromPCPPage().
POMPage::searchInTextAtPosition ($ textPos = -1)
Find the object which contains the requested position in text.
Parameters:
int $textPos The position in the text.
Returns:
array(POMElement, int) The element at the requested position and the number of chars before this element.
Definition at line 545 of file Page.php.
Referenced by addElementAtPosition().
POMPage::sync ()
Copies all texts from the page elements and puts them in the page text attribute.
Returns:
boolean True if synced properly.
Definition at line 529 of file Page.php.
References $__iterator.
Referenced by toString().
POMPage::toString ()
Syncs the page with all its elements and converts them to strings.
Returns:
string The current text representation of the page.
Definition at line 610 of file Page.php.
References sync().
& POMPage::update (POMElement $ element = NULL)
Updates a given element on the page. The element is identified by it's ID.
Parameters:
POMElement $element
Returns:
POMElement The reference to the updated element or NULL.
Definition at line 567 of file Page.php.
References $__iterator.
Member Data Documentation
POMPage::$children [protected]
Definition at line 85 of file Page.php.
The documentation for this class was generated from the following file:
F:/xampp/htdocs/mw/extensions/DataAPI/PageObjectModel/POM/Page.php