PageCRUDPlus: PCPServer Class Reference
PCPServer Class Reference
Inherits PCPAny.
Public Member Functions
PCPServer ()
login (PCPUserCredentials $userCredentials=NULL)
logout (PCPUserCredentials $userCredentials=NULL)
getEditToken (PCPUserCredentials $userCredentials=NULL, $title=NULL)
createPage (PCPUserCredentials $userCredentials=NULL, $title=NULL, $text=NULL, $summary=NULL)
createPages (PCPUserCredentials $userCredentials=NULL, $titles=NULL, $texts=NULL, $summaries=NULL)
& readPage (PCPUserCredentials $userCredentials=NULL, $title=NULL, $revisionID=NULL)
readPages (PCPUserCredentials $userCredentials=NULL, $titles=NULL, $revisionIDs=NULL)
updatePage (PCPUserCredentials $userCredentials=NULL, $title=NULL, $text=NULL, $summary=NULL, $basetimestamp=NULL, $md5_hash=NULL)
updatePages (PCPUserCredentials $userCredentials=NULL, $titles=NULL, $texts=NULL, $summaries=NULL, $basetimestamps=NULL, $md5_hashes=NULL)
deletePage (PCPUserCredentials $userCredentials=NULL, $title=NULL, $reason)
deletePages (PCPUserCredentials $userCredentials=NULL, $titles=NULL, $reasons=NULL)
movePage (PCPUserCredentials $userCredentials=NULL, $fromTitle=NULL, $toTitle=NULL, $movetalk=false, $noredirect=false)
movePages (PCPUserCredentials $userCredentials=NULL, $fromTitles=NULL, $toTitles=NULL, $movetalks=false, $noredirects=false)
Protected Member Functions
setCookies (PCPUserCredentials $userCredentials=NULL)
Protected Attributes
$cookiesSet = false
Detailed Description
The class provides the API functions on the server side.
Author:
Dian
Version:
0.1
Definition at line 11 of file Server.php.
Member Function Documentation
PCPServer::createPage (PCPUserCredentials $ userCredentials = NULL, $ title = NULL, $ text = NULL, $ summary = NULL)
Create a page based on a title and return "true". If the page exists, "false" is returned.
Parameters:
PCPUserCredentials $userCredentials
String $title
String $text
String $summary
Returns:
boolean
Reimplemented from PCPAny.
Definition at line 131 of file Server.php.
References getEditToken(), and PCPUtil::replaceInHash().
Referenced by createPages().
PCPServer::createPages (PCPUserCredentials $ userCredentials = NULL, $ titles = NULL, $ texts = NULL, $ summaries = NULL)
Create pages based on a title and return "true". If a page exists, "false" is returned.
Parameters:
PCPUserCredentials $userCredentials
string[] $titles
string[] $texts
string[] $summaries
Returns:
boolean[]
Reimplemented from PCPAny.
Definition at line 158 of file Server.php.
References createPage().
PCPServer::deletePage (PCPUserCredentials $ userCredentials = NULL, $ title = NULL, $ reason)
Definition at line 309 of file Server.php.
References getEditToken(), and PCPUtil::replaceInHash().
Referenced by deletePages().
PCPServer::deletePages (PCPUserCredentials $ userCredentials = NULL, $ titles = NULL, $ reasons = NULL)
Delete given pages in the wiki.
Parameters:
PCPUserCredentials $userCredentials
string[] $titles
string[] $reasons
Returns:
boolean
Reimplemented from PCPAny.
Definition at line 330 of file Server.php.
References deletePage().
PCPServer::getEditToken (PCPUserCredentials $ userCredentials = NULL, $ title = NULL)
Get the cookies in a forms as described on the MediaWiki API pages.
Returns:
An array with cookies. Set the cookies after a successful login.
Parameters:
PCPUserCredentials $userCredentials Adds the cookies to the PCP object after a login.
PCPUserCredentials $userCredentials Get the edit token for a page.
PCPUserCredentials $userCredentials
string $title
Returns:
PCPUserCredentials The uc including the edit token.
Reimplemented from PCPAny.
Definition at line 85 of file Server.php.
References PCPUtil::replaceInHash(), setCookies(), and PCPUtil::trimFirstTitle().
Referenced by createPage(), deletePage(), movePage(), and updatePage().
PCPServer::login (PCPUserCredentials $ userCredentials = NULL)
Login to a wiki system and save the connection data (cookies).
Parameters:
PCPUserCredentials $userCredentials
Returns:
PCPUserCredentials The uc after the login.
Reimplemented from PCPAny.
Definition at line 46 of file Server.php.
References PCPUtil::replaceInHash(), and setCookies().
PCPServer::logout (PCPUserCredentials $ userCredentials = NULL)
Logout from a wiki system and delete the connection data (cookies).
Parameters:
PCPUserCredentials $userCredentials
Reimplemented from PCPAny.
Definition at line 75 of file Server.php.
References setCookies().
PCPServer::movePage (PCPUserCredentials $ userCredentials = NULL, $ fromTitle = NULL, $ toTitle = NULL, $ movetalk = false, $ noredirect = false)
Get the move token for a page.
Parameters:
string $title
Returns:
PCPUserCredentials The uc including the move token. Move a page in the wiki.
Parameters:
PCPUserCredentials $userCredentials
string $fromTitle
string $toTitle
boolean $movetalk
boolean $noredirect
Returns:
boolean
Reimplemented from PCPAny.
Definition at line 338 of file Server.php.
References getEditToken(), and PCPUtil::replaceInHash().
Referenced by movePages().
PCPServer::movePages (PCPUserCredentials $ userCredentials = NULL, $ fromTitles = NULL, $ toTitles = NULL, $ movetalks = false, $ noredirects = false)
Move pages in the wiki.
Parameters:
PCPUserCredentials $userCredentials
string[] $fromTitles
HashMap(string,string) $toTitles A hashmap with fromTitles as keys and toTitles as values.
HashMap(string,boolean) $movetalks A hashmap with fromTitles as keys and movetalks as values.
HashMap(string,boolean) $noredirects A hashmap with fromTitles as keys and noredirects as values.
Returns:
boolean
Reimplemented from PCPAny.
Definition at line 366 of file Server.php.
References movePage().
PCPServer::PCPServer ()
The class constructor.
Definition at line 24 of file Server.php.
& PCPServer::readPage (PCPUserCredentials $ userCredentials = NULL, $ title = NULL, $ revisionID = NULL)
Read a page from the wiki. If no revisionID given, read the latest revision. Redirects are NOT supported.
Parameters:
PCPUserCredentials $userCredentials
string $title
int $revisionID
Returns:
PCPPage
Reimplemented from PCPAny.
Definition at line 166 of file Server.php.
References PCPUtil::replaceInHash(), setCookies(), and PCPUtil::trimFirstTitle().
Referenced by readPages().
PCPServer::readPages (PCPUserCredentials $ userCredentials = NULL, $ titles = NULL, $ revisionIDs = NULL)
Read pages from the wiki. If no revisionID given, read the latest revision. Redirects are NOT supported.
Parameters:
PCPUserCredentials $userCredentials
string[] $titles
HashMap(string,int) $revisionIDs A hashmap with titles as keys and IDs as values.
Returns:
PCPPage array
Reimplemented from PCPAny.
Definition at line 235 of file Server.php.
References readPage().
PCPServer::setCookies (PCPUserCredentials $ userCredentials = NULL) [protected]
Definition at line 27 of file Server.php.
Referenced by getEditToken(), login(), logout(), and readPage().
PCPServer::updatePage (PCPUserCredentials $ userCredentials = NULL, $ title = NULL, $ text = NULL, $ summary = NULL, $ basetimestamp = NULL, $ md5_hash = NULL)
Update a page in the wiki. If the page doesn't exist, an error occurs. If the basetimestamp is not set, revision conflicts will be ignored. The md5 hash can be set to check if the text is corrupted.
Parameters:
PCPUserCredentials $userCredentials
string $title
string $text
string $summary
string $basetimestamp
string $md5_hash
Returns:
boolean
Reimplemented from PCPAny.
Definition at line 243 of file Server.php.
References getEditToken(), and PCPUtil::replaceInHash().
Referenced by updatePages().
PCPServer::updatePages (PCPUserCredentials $ userCredentials = NULL, $ titles = NULL, $ texts = NULL, $ summaries = NULL, $ basetimestamps = NULL, $ md5_hashes = NULL)
Update pages in the wiki. If a page doesn't exist, an error occurs. If the basetimestamp is not set, revision conflicts will be ignored. The md5 hash can be set to check if the text is corrupted.
Parameters:
PCPUserCredentials $userCredentials
string[] $titles
HashMap(string,string) $texts
HashMap(string,string) $summaries A hashmap with titles as keys and summaries as values.
HashMap(string,string) $basetimestamps A hashmap with titles as keys and base timestamps as values.
HashMap(string,string) $md5_hashes A hashmap with titles as keys and MD5 hashes as values.
Returns:
boolean
Reimplemented from PCPAny.
Definition at line 301 of file Server.php.
References updatePage().
Member Data Documentation
PCPServer::$cookiesSet = false [protected]
Definition at line 18 of file Server.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/mw/extensions/PageCRUD_Plus/PCP/Server.php