PageCRUDPlus: POMExtendedParser Class Reference
POMExtendedParser Class Reference
Inherits POMParser.
Public Member Functions
Parse (POMPage &$page)
Static Public Member Functions
static getParser ()
Protected Member Functions
POMExtendedParser ()
Private Member Functions
doAddWTO (&$wikiText)
maskHTML (&$wikiText)
parseTemplate (&$tokens, $startIndex, $currentlyParsing= 'e')
processTemplateToken (&$token, $currentlyParsing)
findNextState (&$token, &$nextStates, $currentlyParsing)
checkIgnoreAnnotation (&$annotation)
Private Attributes
$mTpState = 0
$mTemplateName = null
$mBracesDropped = false
$mStateMachine
$_page = NULL
Detailed Description
Parser for advanced annotation mode. This parser augments the generated HTML in order to create mapping from HTML to the original wiki text on the client side.
Author:
Dian
Thomas Schweitzer
Definition at line 28 of file ExtendedParser.php.
Member Function Documentation
POMExtendedParser::checkIgnoreAnnotation (&$ annotation) [private]
Checks if the content of an annotation (e.g. [[annotation]]) should be ignored for highlighting. This is used to define exceptions to the normal highlighting of internal wiki links.
Parameters:
string $annotation The annotation to examine.
Returns:
boolean <true>, if the annotation should be ignored <false>, otherwise
Definition at line 709 of file ExtendedParser.php.
POMExtendedParser::doAddWTO (&$ wikiText) [private]
Some wiki text should not be augmented with wiki text offsets. This method defines the exceptions.
Parameters:
string $wikiText The wiki text that will be examined
Returns:
boolean <true>, if the wiki text should be augmented with offsets <false> otherwise
Definition at line 383 of file ExtendedParser.php.
Referenced by Parse().
POMExtendedParser::findNextState (&$ token, &$ nextStates, $ currentlyParsing) [private]
Determines the next state of the template parser by a given token and a set of possible next states.
Parameters:
string $token The next piece of text to examine
array $nextStates Array of possible next states of the state machine.
Returns:
The matching state or <null>.
Definition at line 680 of file ExtendedParser.php.
Referenced by processTemplateToken().
static POMExtendedParser::getParser () [static]
Get an instance of the parser.
Returns:
POMExtendedParser
Definition at line 169 of file ExtendedParser.php.
References POMExtendedParser().
POMExtendedParser::maskHTML (&$ wikiText) [private]
The wiki text <$wikiText> may contain dangerous HTML code, <nowiki>-sections etc.that will confuse the parser that generates wiki text offsets (see addWikiTextOffsets). All dangerous text is replaced by * to keep the number of characters the same.
The following sections are handled:
HTML-comments ()
<nowiki>-sections
<noinclude>-sections
<ask>-sections
-sections
Parameters:
string  $wikiText
Returns:
string masked wiki text
Definition at line 411 of file ExtendedParser.php.
Referenced by Parse().
POMExtendedParser::Parse (POMPage &$ page)
Parses the text of a given page and creates an element structure. Supported types of elements include:
templates,
categories,
properties and
simple text
which represent the rest.
Parameters:
POMPage &$page The page for which the POM will be built.
Reimplemented from POMParser.
Definition at line 185 of file ExtendedParser.php.
References POMPage::addElement(), doAddWTO(), maskHTML(), and parseTemplate().
POMExtendedParser::parseTemplate (&$ tokens, $ startIndex, $ currentlyParsing = 'e') [private]
Tries to parse a template.
Parameters:
array<string> $tokens Array of pieces from the wiki text.
int $startIndex Index where the template parsing starts in <$tokens>
string currentlyParsing The parser is currently parsing a 't' - template 'p' - template parameter 'e' - nothing special
Returns:
array If successful: ('t', templateName, templateStart, templateEnd, templateContent).
Definition at line 499 of file ExtendedParser.php.
References processTemplateToken().
Referenced by Parse().
POMExtendedParser::POMExtendedParser () [protected]
No direct initialization of the parser available.
Returns:
POMExtendedParser
Definition at line 159 of file ExtendedParser.php.
Referenced by getParser().
POMExtendedParser::processTemplateToken (&$ token, $ currentlyParsing) [private]
Templates are parsed with a state machine. The parser is only interested in top level templates, however, they need to be parsed thoroughly to find their end correctly.
Parameters:
string $token The next piece of text to examine
Returns:
array(string,string) <null>, if the template parser is still collecting tokens or an array with three values: 0 - Type of result: t - start of template found at - abort current template candidate p - start of parameter found c - collecting tokens db - drop one opening brace a - append returned token to wiki text et - end of template found ep - end of parameter found 1 - Name of a template or <null> if no template was found 2 - the content of the template or the wiki text that was parsed or <null> if the parser is collecting tokens
Definition at line 624 of file ExtendedParser.php.
References findNextState().
Referenced by parseTemplate().
Member Data Documentation
POMExtendedParser::$_page = NULL [private]
Definition at line 150 of file ExtendedParser.php.
POMExtendedParser::$mBracesDropped = false [private]
Definition at line 37 of file ExtendedParser.php.
POMExtendedParser::$mStateMachine [private]
Definition at line 52 of file ExtendedParser.php.
POMExtendedParser::$mTemplateName = null [private]
Definition at line 34 of file ExtendedParser.php.
POMExtendedParser::$mTpState = 0 [private]
Definition at line 31 of file ExtendedParser.php.
The documentation for this class was generated from the following file:
F:/xampp/htdocs/mw/extensions/DataAPI/PageObjectModel/Parsing/ExtendedParser.php