<?php
/*
 * Copyright (C) Vulcan Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.If not, see <http://www.gnu.org/licenses/>.
 *
 */



global $asfIP;
include_once($asfIP . '/languages/ASF_Language.php');

class ASFLanguageFr extends ASFLanguage {
	
	protected $asfUserMessages = array(
		'asf_free_text' => "Texte libre:",
		'asf_dummy_article_edit_comment' => "Créé par l'extension Formulaire Sémantique Automatique",
		'asf_dummy_article_content' => "'''Cet article est requis par l'extension Formulaire Sémantique Automatique. Veuillez ne pas déplacer, modifier ou supprimer cet article.'''",
		'asf_category_section_label' => "Saisir $1 donnée:",
		'asf_duplicate_property_placeholder' => "Veuillez entrer une valeur dans le champ de saisie ci-dessus.",
		'asf_unresolved_annotations' => "Traiter avec les annotations non résolues:",
		
		'asf_tt_intro' => "Cliquez pour ouvrir $1",
		'asf_tt_type' => "Le <b>type</b> de cette attribut est $1.",
		'asf_tt_autocomplete' => "Ce champ de saisie <b>s'auto-complète automatiquement</b> sur $1.",
		'asf_tt_delimiter' => "Plusieurs valeurs sont autorisées dans ce champ de saisie. \"$1\" est utilisé comme <b>délimiteur</b>.",
	
		'asf_categories_with_no_props_section' => "Catégories pour lesquelles aucun champs de saisie (supplémentaire) de formulaire ne pourront être créés:",
	
		'automaticsemanticforms' => "Formulaire Sémantique Automatique",
		
		'asf_autogenerated_msg' => "<p>'''Ce formulaire a été généré automatiquement.'''</p>"
	);

}