PageObjectModel(POM): DLListIterator Class Reference
DLListIterator Class Reference
Public Member Functions
DLListIterator (&$head, &$list)
hasNext ()
& getNext ()
getNextNodeValue ()
& getNextNodeValueByReference ()
remove ()
hasPrevious ()
& getPrevious ()
Public Attributes
$currentNode
$previousNode
$nextNode
$list
Detailed Description
This class represents an iterator for double linked lists.
Definition at line 414 of file UtilData.php.
Member Function Documentation
DLListIterator::DLListIterator (&$ head, &$ list)
Constructs a ListNode.
Parameters:
&$head The start of the list
&$list The LinkedList, nessesary for updating the size of the list on removal of nodes.
Definition at line 427 of file UtilData.php.
References $list.
& DLListIterator::getNext ()
Get the the next node. Checks if there is a next node, if no next node it returns NULL.
Returns:
The object at current node
Definition at line 451 of file UtilData.php.
References hasNext().
DLListIterator::getNextNodeValue ()
Get the value of the next node. Checks if there is a next node, if no next node it returns NULL.
Returns:
The object at the current node
Definition at line 474 of file UtilData.php.
References hasNext().
& DLListIterator::getNextNodeValueByReference ()
Get the reference to the value of the next node. Checks if there is a next node, if no next node it returns NULL.
Returns:
The object at the current node
Definition at line 497 of file UtilData.php.
References hasNext().
& DLListIterator::getPrevious ()
Get the reference to the previous node.
Parameters:
&$node The next node. || FALSE if no next node exists.
Definition at line 549 of file UtilData.php.
References hasPrevious().
DLListIterator::hasNext ()
Checks if more nodes exist
Returns:
TRUE == hasNext || FALSE == no next node.
Definition at line 440 of file UtilData.php.
Referenced by getNext(), getNextNodeValue(), and getNextNodeValueByReference().
DLListIterator::hasPrevious ()
Checks if more nodes exist
Returns:
TRUE == hasNext || FALSE == no next node.
Definition at line 540 of file UtilData.php.
Referenced by getPrevious().
DLListIterator::remove ()
Removes the current node Uses the list removeObjectAtIndex it it is the head or tail that is to be removed.
Definition at line 519 of file UtilData.php.
Member Data Documentation
DLListIterator::$currentNode
Definition at line 416 of file UtilData.php.
DLListIterator::$list
Definition at line 419 of file UtilData.php.
Referenced by DLListIterator().
DLListIterator::$nextNode
Definition at line 418 of file UtilData.php.
DLListIterator::$previousNode
Definition at line 417 of file UtilData.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/mw/extensions/PageObjectModel/Util/UtilData.php