PageObjectModel(POM): POMPageWS_API Class Reference
POMPageWS_API Class Reference
Public Member Functions
__construct ($query, $moduleName)
execute ()
getVersion ()
Protected Member Functions
getAllowedParams ()
getParamDescription ()
getDescription ()
getExamples ()
createPage ($username=NULL, $password=NULL, $id=NULL, $loginToken=NULL, $editToken=NULL, $title=NULL, $text=NULL, $summary=NULL)
getElements ($username=NULL, $password=NULL, $id=NULL, $loginToken=NULL, $editToken=NULL, $title=NULL, $revisionID=NULL)
getTemplates ($username=NULL, $password=NULL, $id=NULL, $loginToken=NULL, $editToken=NULL, $title=NULL, $revisionID=NULL)
getTemplateByTitle ($username=NULL, $password=NULL, $id=NULL, $loginToken=NULL, $editToken=NULL, $title=NULL, $revisionID=NULL, $templateTitle=NULL)
getProperties ($username=NULL, $password=NULL, $id=NULL, $loginToken=NULL, $editToken=NULL, $title=NULL, $revisionID=NULL)
getPropertyByName ($username=NULL, $password=NULL, $id=NULL, $loginToken=NULL, $editToken=NULL, $title=NULL, $revisionID=NULL, $propertyName=NULL)
getCategories ($username=NULL, $password=NULL, $id=NULL, $loginToken=NULL, $editToken=NULL, $title=NULL, $revisionID=NULL)
getCategoryByName ($username=NULL, $password=NULL, $id=NULL, $loginToken=NULL, $editToken=NULL, $title=NULL, $revisionID=NULL, $categoryName=NULL)
getSimpleTexts ($username=NULL, $password=NULL, $id=NULL, $loginToken=NULL, $editToken=NULL, $title=NULL, $revisionID=NULL)
Private Member Functions
toArray ($data)
Detailed Description
Definition at line 19 of file PageAPI.php.
Constructor & Destructor Documentation
POMPageWS_API::__construct ($ query, $ moduleName)
Definition at line 21 of file PageAPI.php.
Member Function Documentation
POMPageWS_API::createPage ($ username = NULL, $ password = NULL, $ id = NULL, $ loginToken = NULL, $ editToken = NULL, $ title = NULL, $ text = NULL, $ summary = NULL) [protected]
Definition at line 183 of file PageAPI.php.
POMPageWS_API::execute ()
Definition at line 25 of file PageAPI.php.
References getCategories(), getCategoryByName(), getElements(), getProperties(), getPropertyByName(), getSimpleTexts(), getTemplateByTitle(), and getTemplates().
POMPageWS_API::getAllowedParams () [protected]
Definition at line 129 of file PageAPI.php.
POMPageWS_API::getCategories ($ username = NULL, $ password = NULL, $ id = NULL, $ loginToken = NULL, $ editToken = NULL, $ title = NULL, $ revisionID = NULL) [protected]
Definition at line 260 of file PageAPI.php.
References toArray().
Referenced by execute().
POMPageWS_API::getCategoryByName ($ username = NULL, $ password = NULL, $ id = NULL, $ loginToken = NULL, $ editToken = NULL, $ title = NULL, $ revisionID = NULL, $ categoryName = NULL) [protected]
Definition at line 275 of file PageAPI.php.
References toArray().
Referenced by execute().
POMPageWS_API::getDescription () [protected]
Definition at line 169 of file PageAPI.php.
POMPageWS_API::getElements ($ username = NULL, $ password = NULL, $ id = NULL, $ loginToken = NULL, $ editToken = NULL, $ title = NULL, $ revisionID = NULL) [protected]
Definition at line 190 of file PageAPI.php.
References toArray().
Referenced by execute().
POMPageWS_API::getExamples () [protected]
Definition at line 173 of file PageAPI.php.
POMPageWS_API::getParamDescription () [protected]
Definition at line 151 of file PageAPI.php.
POMPageWS_API::getProperties ($ username = NULL, $ password = NULL, $ id = NULL, $ loginToken = NULL, $ editToken = NULL, $ title = NULL, $ revisionID = NULL) [protected]
Definition at line 232 of file PageAPI.php.
References toArray().
Referenced by execute().
POMPageWS_API::getPropertyByName ($ username = NULL, $ password = NULL, $ id = NULL, $ loginToken = NULL, $ editToken = NULL, $ title = NULL, $ revisionID = NULL, $ propertyName = NULL) [protected]
Definition at line 246 of file PageAPI.php.
References toArray().
Referenced by execute().
POMPageWS_API::getSimpleTexts ($ username = NULL, $ password = NULL, $ id = NULL, $ loginToken = NULL, $ editToken = NULL, $ title = NULL, $ revisionID = NULL) [protected]
Definition at line 289 of file PageAPI.php.
References toArray().
Referenced by execute().
POMPageWS_API::getTemplateByTitle ($ username = NULL, $ password = NULL, $ id = NULL, $ loginToken = NULL, $ editToken = NULL, $ title = NULL, $ revisionID = NULL, $ templateTitle = NULL) [protected]
Definition at line 218 of file PageAPI.php.
References toArray().
Referenced by execute().
POMPageWS_API::getTemplates ($ username = NULL, $ password = NULL, $ id = NULL, $ loginToken = NULL, $ editToken = NULL, $ title = NULL, $ revisionID = NULL) [protected]
Definition at line 204 of file PageAPI.php.
References toArray().
Referenced by execute().
POMPageWS_API::getVersion ()
Definition at line 180 of file PageAPI.php.
POMPageWS_API::toArray ($ data) [private]
Definition at line 305 of file PageAPI.php.
Referenced by getCategories(), getCategoryByName(), getElements(), getProperties(), getPropertyByName(), getSimpleTexts(), getTemplateByTitle(), and getTemplates().
The documentation for this class was generated from the following file:
C:/xampp/htdocs/mw/extensions/PageObjectModel/WS/PageAPI.php