<?php
/*
 * Copyright (C) Vulcan Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.If not, see <http://www.gnu.org/licenses/>.
 *
 */

 
if ( !defined( 'MEDIAWIKI' ) ) {
    die( 'This file is a MediaWiki extension, it is not a valid entry point' );
}
 
$wgExtensionFunctions[] = 'wfSetupDebugTemplate';
 
$wgExtensionCredits['parserhook'][] = array(
        'name' => 'Debug Template',
        'url' => 'http://www.mediawiki.org/wiki/Extension:DebugTemplate',
        'author'=>"Maintained by [http://smwplus.com ontoprise GmbH].", 
        'description' => 'Show the wikitext that is generated by templates and parser functions.'
);
 
$wgHooks['LanguageGetMagic'][]       = 'wfDebugTemplateLanguageGetMagic';
 
class ExtDebugTemplate {
 
    function debugTemplate( &$parser, $wikiText ) {
        return '<pre>'.$wikiText.'</pre>';
    }
 }
 
function wfSetupDebugTemplate() {
    global $wgParser, $wgExtDebugTemplate, $wgHooks;
 
    $wgExtDebugTemplate = new ExtDebugTemplate;
 
    $wgParser->setFunctionHook( 'debugTemplate', array( &$wgExtDebugTemplate, 'debugTemplate' ) );
}
 
function wfDebugTemplateLanguageGetMagic( &$magicWords, $langCode ) {
        require_once( dirname( __FILE__ ) . '/DebugTemplate.i18n.php' );
        foreach( efDebugTemplateWords( $langCode ) as $word => $trans )
                $magicWords[$word] = $trans;
        return true;
}
 
?>
