var config={},tt_Debug=false,tt_Enabled=true,TagsToTip=true;config.Above=false;config.BgColor="#E4E7FF";config.BgImg="";config.BorderColor="#002299";config.BorderStyle="solid";config.BorderWidth=1;config.CenterMouse=false;config.ClickClose=false;config.CloseBtn=false;config.CloseBtnColors=["#990000","#FFFFFF","#DD3333","#FFFFFF"];config.CloseBtnText="&nbsp;X&nbsp;";config.CopyContent=true;config.Delay=400;config.Duration=0;config.FadeIn=0;config.FadeOut=0;config.FadeInterval=30;config.Fix=null;
config.FollowMouse=true;config.FontColor="#000044";config.FontFace="Verdana,Geneva,sans-serif";config.FontSize="8pt";config.FontWeight="normal";config.Left=false;config.OffsetX=14;config.OffsetY=8;config.Opacity=100;config.Padding=3;config.Shadow=false;config.ShadowColor="#C0C0C0";config.ShadowWidth=5;config.Sticky=false;config.TextAlign="left";config.Title="";config.TitleAlign="left";config.TitleBgColor="";config.TitleFontColor="#ffffff";config.TitleFontFace="";config.TitleFontSize="";
config.Width=200;function Tip(){tt_Tip(arguments,null)}function TagToTip(){if(TagsToTip){var a=tt_GetElt(arguments[0]);a&&tt_Tip(arguments,a)}}var tt_aElt=Array(10),tt_aV=[],tt_sContent,tt_scrlX=0,tt_scrlY=0,tt_musX,tt_musY,tt_over,tt_x,tt_y,tt_w,tt_h;function tt_Extension(){tt_ExtCmdEnum();tt_aExt[tt_aExt.length]=this;return this}
function tt_SetTipPos(a,b){var c=tt_aElt[0].style;tt_x=a;tt_y=b;c.left=a+"px";c.top=b+"px";if(tt_ie56){var d=tt_aElt[tt_aElt.length-1];if(d){d.style.left=c.left;d.style.top=c.top}}}
function tt_Hide(){if(tt_db&&tt_iState){if(tt_iState&2){tt_aElt[0].style.visibility="hidden";tt_ExtCallFncs(0,"Hide")}tt_tShow.EndTimer();tt_tHide.EndTimer();tt_tDurt.EndTimer();tt_tFade.EndTimer();if(!tt_op&&!tt_ie){tt_tWaitMov.EndTimer();tt_bWait=false}tt_aV[CLICKCLOSE]&&tt_RemEvtFnc(document,"mouseup",tt_HideInit);tt_AddRemOutFnc(false);tt_ExtCallFncs(0,"Kill");if(tt_t2t&&!tt_aV[COPYCONTENT]){tt_t2t.style.display="none";tt_MovDomNode(tt_t2t,tt_aElt[6],tt_t2tDad)}tt_iState=0;tt_over=null;tt_ResetMainDiv();
if(tt_aElt[tt_aElt.length-1])tt_aElt[tt_aElt.length-1].style.display="none"}}function tt_GetElt(a){return document.getElementById?document.getElementById(a):document.all?document.all[a]:null}function tt_GetDivW(a){return a?a.offsetWidth||a.style.pixelWidth||0:0}function tt_GetDivH(a){return a?a.offsetHeight||a.style.pixelHeight||0:0}function tt_GetScrollX(){return window.pageXOffset||(tt_db?tt_db.scrollLeft||0:0)}function tt_GetScrollY(){return window.pageYOffset||(tt_db?tt_db.scrollTop||0:0)}
function tt_GetClientW(){return document.body&&typeof document.body.clientWidth!=tt_u?document.body.clientWidth:typeof window.innerWidth!=tt_u?window.innerWidth:tt_db?tt_db.clientWidth||0:0}function tt_GetClientH(){return document.body&&typeof document.body.clientHeight!=tt_u?document.body.clientHeight:typeof window.innerHeight!=tt_u?window.innerHeight:tt_db?tt_db.clientHeight||0:0}function tt_GetEvtX(a){return a?typeof a.pageX!=tt_u?a.pageX:a.clientX+tt_scrlX:0}
function tt_GetEvtY(a){return a?typeof a.pageY!=tt_u?a.pageY:a.clientY+tt_scrlY:0}function tt_AddEvtFnc(a,b,c){if(a)a.addEventListener?a.addEventListener(b,c,false):a.attachEvent("on"+b,c)}function tt_RemEvtFnc(a,b,c){if(a)a.removeEventListener?a.removeEventListener(b,c,false):a.detachEvent("on"+b,c)}
var tt_aExt=[],tt_db,tt_op,tt_ie,tt_ie56,tt_bBoxOld,tt_body,tt_flagOpa,tt_maxPosX,tt_maxPosY,tt_iState=0,tt_opa,tt_bJmpVert,tt_t2t,tt_t2tDad,tt_elDeHref,tt_tShow=new Number(0),tt_tHide=new Number(0),tt_tDurt=new Number(0),tt_tFade=new Number(0),tt_tWaitMov=new Number(0),tt_bWait=false,tt_u="undefined";
function tt_Init(){tt_MkCmdEnum();if(tt_Browser()&&tt_MkMainDiv()){tt_IsW3cBox();tt_OpaSupport();tt_AddEvtFnc(document,"mousemove",tt_Move);if(TagsToTip||tt_Debug)tt_SetOnloadFnc();tt_AddEvtFnc(window,"scroll",function(){tt_scrlX=tt_GetScrollX();tt_scrlY=tt_GetScrollY();tt_iState&&!(tt_aV[STICKY]&&tt_iState&2)&&tt_HideInit()});tt_AddEvtFnc(window,"unload",tt_Hide);tt_Hide()}}function tt_MkCmdEnum(){var a=0;for(var b in config)eval("window."+b.toString().toUpperCase()+" = "+a++);tt_aV.length=a}
function tt_Browser(){var a,b,c,d;a=navigator.userAgent.toLowerCase();b=navigator.appVersion;tt_op=document.defaultView&&typeof eval("window.opera")!=tt_u;if(tt_ie=a.indexOf("msie")!=-1&&document.all&&!tt_op){if(tt_db=!(!document.compatMode||document.compatMode=="BackCompat")?document.documentElement:document.body||null)tt_ie56=parseFloat(b.substring(b.indexOf("MSIE")+5))>=5.5&&typeof document.body.style.maxHeight==tt_u}else{tt_db=document.documentElement||document.body||(document.getElementsByTagName?
document.getElementsByTagName("body")[0]:null);if(!tt_op){c=document.defaultView&&typeof document.defaultView.getComputedStyle!=tt_u;d=!c&&document.getElementById}}tt_body=document.getElementsByTagName?document.getElementsByTagName("body")[0]:document.body||null;if(tt_ie||c||tt_op||d)if(tt_body&&tt_db){if(document.attachEvent||document.addEventListener)return true}else tt_Err("wz_tooltip.js must be included INSIDE the body section, immediately after the opening <body> tag.");tt_db=null;return false}
function tt_MkMainDiv(){if(tt_body.insertAdjacentHTML)tt_body.insertAdjacentHTML("afterBegin",tt_MkMainDivHtm());else typeof tt_body.innerHTML!=tt_u&&document.createElement&&tt_body.appendChild&&tt_body.appendChild(tt_MkMainDivDom());if(window.tt_GetMainDivRefs&&tt_GetMainDivRefs())return true;tt_db=null;return false}
function tt_MkMainDivHtm(){return'<div id="WzTtDiV"></div>'+(tt_ie56?'<iframe id="WzTtIfRm" src="javascript:false" scrolling="no" frameborder="0" style="filter:Alpha(opacity=0);position:absolute;top:0px;left:0px;display:none;"></iframe>':"")}function tt_MkMainDivDom(){var a=document.createElement("div");if(a)a.id="WzTtDiV";return a}
function tt_GetMainDivRefs(){tt_aElt[0]=tt_GetElt("WzTtDiV");if(tt_ie56&&tt_aElt[0]){tt_aElt[tt_aElt.length-1]=tt_GetElt("WzTtIfRm");tt_aElt[tt_aElt.length-1]||(tt_aElt[0]=null)}if(tt_aElt[0]){var a=tt_aElt[0].style;a.visibility="hidden";a.position="absolute";a.overflow="hidden";return true}return false}function tt_ResetMainDiv(){var a=window.screen&&screen.width?screen.width:1E4;tt_SetTipPos(-a,0);tt_aElt[0].innerHTML="";tt_aElt[0].style.width=a-1+"px"}
function tt_IsW3cBox(){var a=tt_aElt[0].style;a.padding="10px";a.width="40px";tt_bBoxOld=tt_GetDivW(tt_aElt[0])==40;a.padding="0px";tt_ResetMainDiv()}function tt_OpaSupport(){var a=tt_body.style;tt_flagOpa=typeof a.filter!=tt_u?1:typeof a.KhtmlOpacity!=tt_u?2:typeof a.KHTMLOpacity!=tt_u?3:typeof a.MozOpacity!=tt_u?4:typeof a.opacity!=tt_u?5:0}
function tt_SetOnloadFnc(){tt_AddEvtFnc(document,"DOMContentLoaded",tt_HideSrcTags);tt_AddEvtFnc(window,"load",tt_HideSrcTags);tt_body.attachEvent&&tt_body.attachEvent("onreadystatechange",function(){tt_body.readyState=="complete"&&tt_HideSrcTags()});if(/WebKit|KHTML/i.test(navigator.userAgent))var a=setInterval(function(){if(/loaded|complete/.test(document.readyState)){clearInterval(a);tt_HideSrcTags()}},10)}
function tt_HideSrcTags(){if(!(!window.tt_HideSrcTags||window.tt_HideSrcTags.done)){window.tt_HideSrcTags.done=true;tt_HideSrcTagsRecurs(tt_body)||tt_Err("To enable the capability to convert HTML elements to tooltips, you must set TagsToTip in the global tooltip configuration to true.")}}
function tt_HideSrcTagsRecurs(a){var b;for(var c=(a=a.childNodes||a.children||null)?a.length:0;c;){--c;if(!tt_HideSrcTagsRecurs(a[c]))return false;if(b=a[c].getAttribute?a[c].getAttribute("onmouseover"):typeof a[c].onmouseover=="function"?a[c].onmouseover:null)if((b=b.toString().match(/TagToTip\s*\(\s*'[^'.]+'\s*[\),]/))&&b.length)if(!tt_HideSrcTag(b[0]))return false}return true}
function tt_HideSrcTag(a){var b;a=a.replace(/.+'([^'.]+)'.+/,"$1");if(b=tt_GetElt(a))if(tt_Debug&&!TagsToTip)return false;else b.style.display="none";else tt_Err("Invalid ID\n'"+a+"'\npassed to TagToTip(). There exists no HTML element with that ID.");return true}
function tt_Tip(a,b){if(tt_db){tt_iState&&tt_Hide();if(tt_Enabled){tt_t2t=b;if(tt_ReadCmds(a)){tt_iState=5;tt_AdaptConfig1();tt_MkTipContent(a);tt_MkTipSubDivs();tt_FormatTip();tt_bJmpVert=false;tt_maxPosX=tt_GetClientW()+tt_scrlX-tt_w-1;tt_maxPosY=tt_GetClientH()+tt_scrlY-tt_h-1;tt_AdaptConfig2();tt_Move();tt_ShowInit()}}}}
function tt_ReadCmds(a){var b;b=0;for(var c in config)tt_aV[b++]=config[c];if(a.length&1){for(b=a.length-1;b>0;b-=2)tt_aV[a[b-1]]=a[b];return true}tt_Err("Incorrect call of Tip() or TagToTip().\nEach command must be followed by a value.");return false}
function tt_AdaptConfig1(){tt_ExtCallFncs(0,"LoadConfig");tt_aV[TITLEBGCOLOR].length||(tt_aV[TITLEBGCOLOR]=tt_aV[BORDERCOLOR]);tt_aV[TITLEFONTCOLOR].length||(tt_aV[TITLEFONTCOLOR]=tt_aV[BGCOLOR]);tt_aV[TITLEFONTFACE].length||(tt_aV[TITLEFONTFACE]=tt_aV[FONTFACE]);tt_aV[TITLEFONTSIZE].length||(tt_aV[TITLEFONTSIZE]=tt_aV[FONTSIZE]);if(tt_aV[CLOSEBTN]){tt_aV[CLOSEBTNCOLORS]||(tt_aV[CLOSEBTNCOLORS]=Array("","","",""));for(var a=4;a;){--a;tt_aV[CLOSEBTNCOLORS][a].length||(tt_aV[CLOSEBTNCOLORS][a]=a&1?
tt_aV[TITLEFONTCOLOR]:tt_aV[TITLEBGCOLOR])}tt_aV[TITLE].length||(tt_aV[TITLE]=" ")}if(tt_aV[OPACITY]==100&&typeof tt_aElt[0].style.MozOpacity!=tt_u&&!Array.every)tt_aV[OPACITY]=99;if(tt_aV[FADEIN]&&tt_flagOpa&&tt_aV[DELAY]>100)tt_aV[DELAY]=Math.max(tt_aV[DELAY]-tt_aV[FADEIN],100)}function tt_AdaptConfig2(){if(tt_aV[CENTERMOUSE])tt_aV[OFFSETX]-=tt_w-(tt_aV[SHADOW]?tt_aV[SHADOWWIDTH]:0)>>1}
function tt_MkTipContent(a){tt_sContent=tt_t2t?tt_aV[COPYCONTENT]?tt_t2t.innerHTML:"":a[0];tt_ExtCallFncs(0,"CreateContentString")}
function tt_MkTipSubDivs(){tt_aElt[0].innerHTML=""+(tt_aV[TITLE].length?'<div id="WzTiTl" style="position:relative;z-index:1;"><table id="WzTiTlTb" cellspacing=0 cellpadding=0 border=0 style="position:relative;margin:0px;padding:0px;border-width:0px;left:0px;top:0px;line-height:normal;width:auto;"><tbody style="position:relative;margin:0px;padding:0px;border-width:0px;left:0px;top:0px;line-height:normal;width:auto;"><tr><td id="WzTiTlI" style="position:relative;margin:0px;padding:0px;border-width:0px;left:0px;top:0px;line-height:normal;width:auto;">'+tt_aV[TITLE]+
"</td>"+(tt_aV[CLOSEBTN]?'<td align="right" style="position:relative;margin:0px;padding:0px;border-width:0px;left:0px;top:0px;line-height:normal;width:auto;text-align:right;"><span id="WzClOsE" style="padding-left:2px;padding-right:2px;cursor:'+(tt_ie?"hand":"pointer")+';" onmouseover="tt_OnCloseBtnOver(1)" onmouseout="tt_OnCloseBtnOver(0)" onclick="tt_HideInit()">'+tt_aV[CLOSEBTNTEXT]+"</span></td>":"")+"</tr></tbody></table></div>":"")+'<div id="WzBoDy" style="position:relative;z-index:0;"><table cellspacing=0 cellpadding=0 border=0 style="position:relative;margin:0px;padding:0px;border-width:0px;left:0px;top:0px;line-height:normal;width:auto;"><tbody style="position:relative;margin:0px;padding:0px;border-width:0px;left:0px;top:0px;line-height:normal;width:auto;"><tr><td id="WzBoDyI" style="position:relative;margin:0px;padding:0px;border-width:0px;left:0px;top:0px;line-height:normal;width:auto;">'+
tt_sContent+"</td></tr></tbody></table></div>"+(tt_aV[SHADOW]?'<div id="WzTtShDwR" style="position:absolute;overflow:hidden;"></div><div id="WzTtShDwB" style="position:relative;overflow:hidden;"></div>':"");tt_GetSubDivRefs();if(tt_t2t&&!tt_aV[COPYCONTENT])if(tt_t2tDad=tt_t2t.parentNode||tt_t2t.parentElement||tt_t2t.offsetParent||null){tt_MovDomNode(tt_t2t,tt_t2tDad,tt_aElt[6]);tt_t2t.style.display="block"}tt_ExtCallFncs(0,"SubDivsCreated")}
function tt_GetSubDivRefs(){for(var a=Array("WzTiTl","WzTiTlTb","WzTiTlI","WzClOsE","WzBoDy","WzBoDyI","WzTtShDwB","WzTtShDwR"),b=a.length;b;--b)tt_aElt[b]=tt_GetElt(a[b-1])}
function tt_FormatTip(){var a,b,c;if(tt_aV[TITLE].length){a=tt_aElt[1].style;a.background=tt_aV[TITLEBGCOLOR];a.paddingTop=(tt_aV[CLOSEBTN]?2:0)+"px";a.paddingBottom="1px";a.paddingLeft=a.paddingRight=tt_aV[PADDING]+"px";a=tt_aElt[3].style;a.color=tt_aV[TITLEFONTCOLOR];a.fontFamily=tt_aV[TITLEFONTFACE];a.fontSize=tt_aV[TITLEFONTSIZE];a.fontWeight="bold";a.textAlign=tt_aV[TITLEALIGN];if(tt_aElt[4]){a.paddingRight=(tt_aV[PADDING]<<1)+"px";a=tt_aElt[4].style;a.background=tt_aV[CLOSEBTNCOLORS][0];a.color=
tt_aV[CLOSEBTNCOLORS][1];a.fontFamily=tt_aV[TITLEFONTFACE];a.fontSize=tt_aV[TITLEFONTSIZE];a.fontWeight="bold"}if(tt_aV[WIDTH]>0)tt_w=tt_aV[WIDTH]+(tt_aV[PADDING]+tt_aV[BORDERWIDTH]<<1);else{tt_w=tt_GetDivW(tt_aElt[3])+tt_GetDivW(tt_aElt[4]);if(tt_aElt[4])tt_w+=tt_aV[PADDING]}b=-tt_aV[BORDERWIDTH]}else b=tt_w=0;a=tt_aElt[5].style;a.top=b+"px";if(tt_aV[BORDERWIDTH]){a.borderColor=tt_aV[BORDERCOLOR];a.borderStyle=tt_aV[BORDERSTYLE];a.borderWidth=tt_aV[BORDERWIDTH]+"px"}if(tt_aV[BGCOLOR].length)a.background=
tt_aV[BGCOLOR];if(tt_aV[BGIMG].length)a.backgroundImage="url("+tt_aV[BGIMG]+")";a.padding=tt_aV[PADDING]+"px";a.textAlign=tt_aV[TEXTALIGN];a=tt_aElt[6].style;a.color=tt_aV[FONTCOLOR];a.fontFamily=tt_aV[FONTFACE];a.fontSize=tt_aV[FONTSIZE];a.fontWeight=tt_aV[FONTWEIGHT];a.background="";a.textAlign=tt_aV[TEXTALIGN];a=tt_aV[WIDTH]>0?tt_aV[WIDTH]+(tt_aV[PADDING]+tt_aV[BORDERWIDTH]<<1):tt_GetDivW(tt_aElt[6])+(tt_aV[PADDING]+tt_aV[BORDERWIDTH]<<1);if(a>tt_w)tt_w=a;if(tt_aV[SHADOW]){tt_w+=tt_aV[SHADOWWIDTH];
c=Math.floor(tt_aV[SHADOWWIDTH]*4/3);a=tt_aElt[7].style;a.top=b+"px";a.left=c+"px";a.width=tt_w-c-tt_aV[SHADOWWIDTH]+"px";a.height=tt_aV[SHADOWWIDTH]+"px";a.background=tt_aV[SHADOWCOLOR];a=tt_aElt[8].style;a.top=c+"px";a.left=tt_w-tt_aV[SHADOWWIDTH]+"px";a.width=tt_aV[SHADOWWIDTH]+"px";a.background=tt_aV[SHADOWCOLOR]}else c=0;tt_SetTipOpa(tt_aV[FADEIN]?0:tt_aV[OPACITY]);tt_FixSize(b,c)}
function tt_FixSize(a,b){var c,d;tt_aElt[0].style.width=tt_w+"px";tt_aElt[0].style.pixelWidth=tt_w;c=d=tt_w-(tt_aV[SHADOW]?tt_aV[SHADOWWIDTH]:0);tt_bBoxOld||(c-=tt_aV[PADDING]+tt_aV[BORDERWIDTH]<<1);tt_aElt[5].style.width=c+"px";if(tt_aElt[1]){c=d-(tt_aV[PADDING]<<1);tt_bBoxOld||(d=c);tt_aElt[1].style.width=d+"px";tt_aElt[2].style.width=c+"px"}tt_h=tt_GetDivH(tt_aElt[0])+a;if(tt_aElt[8])tt_aElt[8].style.height=tt_h-b+"px";c=tt_aElt.length-1;if(tt_aElt[c]){tt_aElt[c].style.width=tt_w+"px";tt_aElt[c].style.height=
tt_h+"px"}}function tt_DeAlt(a){if(a.alt)a.alt="";if(a.title)a.title="";if(a=a.childNodes||a.children||null)for(var b=a.length;b;)tt_DeAlt(a[--b])}function tt_OpDeHref(a){if(tt_op)for(tt_elDeHref&&tt_OpReHref();a;){if(a.hasAttribute("href")){a.t_href=a.getAttribute("href");a.t_stats=window.status;a.removeAttribute("href");a.style.cursor="hand";tt_AddEvtFnc(a,"mousedown",tt_OpReHref);window.status=a.t_href;tt_elDeHref=a;break}a=a.parentElement}}
function tt_ShowInit(){tt_tShow.Timer("tt_Show()",tt_aV[DELAY],true);tt_aV[CLICKCLOSE]&&tt_AddEvtFnc(document,"mouseup",tt_HideInit)}function tt_OverInit(a){tt_over=a.target||a.srcElement;tt_DeAlt(tt_over);tt_OpDeHref(tt_over);tt_AddRemOutFnc(true)}
function tt_Show(){var a=tt_aElt[0].style;a.zIndex=Math.max(window.dd&&dd.z?dd.z+2:0,1010);if(tt_aV[STICKY]||!tt_aV[FOLLOWMOUSE])tt_iState&=-5;tt_aV[DURATION]>0&&tt_tDurt.Timer("tt_HideInit()",tt_aV[DURATION],true);tt_ExtCallFncs(0,"Show");a.visibility="visible";tt_iState|=2;tt_aV[FADEIN]&&tt_Fade(0,0,tt_aV[OPACITY],Math.round(tt_aV[FADEIN]/tt_aV[FADEINTERVAL]));tt_ShowIfrm()}
function tt_ShowIfrm(){if(tt_ie56){var a=tt_aElt[tt_aElt.length-1];if(a){a=a.style;a.zIndex=tt_aElt[0].style.zIndex-1;a.display="block"}}}
function tt_Move(a){if(a=window.event||a){tt_musX=tt_GetEvtX(a);tt_musY=tt_GetEvtY(a)}if(tt_iState){!tt_over&&a&&tt_OverInit(a);if(tt_iState&4){if(!tt_op&&!tt_ie){if(tt_bWait)return;tt_bWait=true;tt_tWaitMov.Timer("tt_bWait = false;",1,true)}if(tt_aV[FIX]){tt_iState&=-5;tt_SetTipPos(tt_aV[FIX][0],tt_aV[FIX][1])}else tt_ExtCallFncs(a,"MoveBefore")||tt_SetTipPos(tt_PosX(),tt_PosY());tt_ExtCallFncs([tt_musX,tt_musY],"MoveAfter")}}}
function tt_PosX(){var a;a=tt_musX;if(tt_aV[LEFT])a-=tt_w+tt_aV[OFFSETX]-(tt_aV[SHADOW]?tt_aV[SHADOWWIDTH]:0);else a+=tt_aV[OFFSETX];if(a>tt_maxPosX)a=tt_maxPosX;return a<tt_scrlX?tt_scrlX:a}function tt_PosY(){var a;a=tt_aV[ABOVE]&&(!tt_bJmpVert||tt_CalcPosYAbove()>=tt_scrlY+16)?tt_DoPosYAbove():!tt_aV[ABOVE]&&tt_bJmpVert&&tt_CalcPosYBelow()>tt_maxPosY-16?tt_DoPosYAbove():tt_DoPosYBelow();if(a>tt_maxPosY)a=tt_DoPosYAbove();if(a<tt_scrlY)a=tt_DoPosYBelow();return a}
function tt_DoPosYBelow(){tt_bJmpVert=tt_aV[ABOVE];return tt_CalcPosYBelow()}function tt_DoPosYAbove(){tt_bJmpVert=!tt_aV[ABOVE];return tt_CalcPosYAbove()}function tt_CalcPosYBelow(){return tt_musY+tt_aV[OFFSETY]}function tt_CalcPosYAbove(){var a=tt_aV[OFFSETY]-(tt_aV[SHADOW]?tt_aV[SHADOWWIDTH]:0);if(tt_aV[OFFSETY]>0&&a<=0)a=1;return tt_musY-tt_h-a}function tt_OnOut(){tt_AddRemOutFnc(false);tt_aV[STICKY]&&tt_iState&2||tt_HideInit()}
function tt_HideInit(){tt_ExtCallFncs(0,"HideInit");tt_iState&=-5;if(tt_flagOpa&&tt_aV[FADEOUT]){tt_tFade.EndTimer();if(tt_opa){tt_Fade(tt_opa,tt_opa,0,Math.round(tt_aV[FADEOUT]/(tt_aV[FADEINTERVAL]*(tt_aV[OPACITY]/tt_opa))));return}}tt_tHide.Timer("tt_Hide();",1,false)}function tt_OpReHref(){if(tt_elDeHref){tt_elDeHref.setAttribute("href",tt_elDeHref.t_href);tt_RemEvtFnc(tt_elDeHref,"mousedown",tt_OpReHref);window.status=tt_elDeHref.t_stats;tt_elDeHref=null}}
function tt_Fade(a,b,c,d){if(d){b+=Math.round((c-b)/d);if(c>a?b>=c:b<=c)b=c;else tt_tFade.Timer("tt_Fade("+a+","+b+","+c+","+(d-1)+")",tt_aV[FADEINTERVAL],true)}b?tt_SetTipOpa(b):tt_Hide()}function tt_SetTipOpa(a){tt_SetOpa(tt_aElt[5].style,a);tt_aElt[1]&&tt_SetOpa(tt_aElt[1].style,a);if(tt_aV[SHADOW]){a=Math.round(a*0.8);tt_SetOpa(tt_aElt[7].style,a);tt_SetOpa(tt_aElt[8].style,a)}}
function tt_OnCloseBtnOver(a){var b=tt_aElt[4].style;a<<=1;b.background=tt_aV[CLOSEBTNCOLORS][a];b.color=tt_aV[CLOSEBTNCOLORS][a+1]}function tt_Int(a){var b;return isNaN(b=parseInt(a))?0:b}function tt_AddRemOutFnc(a){var b=a?tt_AddEvtFnc:tt_RemEvtFnc;if(a!=tt_AddRemOutFnc.bOn){b(tt_over,"mouseout",tt_OnOut);(tt_AddRemOutFnc.bOn=a)||tt_OpReHref()}}tt_AddRemOutFnc.bOn=false;Number.prototype.Timer=function(a,b,c){if(!this.value||c)this.value=window.setTimeout(a,b)};
Number.prototype.EndTimer=function(){if(this.value){window.clearTimeout(this.value);this.value=0}};function tt_SetOpa(a,b){tt_opa=b;if(tt_flagOpa==1)if(b<100){var c=a.visibility!="hidden";a.zoom="100%";if(!c)a.visibility="visible";a.filter="alpha(opacity="+b+")";if(!c)a.visibility="hidden"}else a.filter="";else{b/=100;switch(tt_flagOpa){case 2:a.KhtmlOpacity=b;break;case 3:a.KHTMLOpacity=b;break;case 4:a.MozOpacity=b;break;case 5:a.opacity=b;break}}}
function tt_MovDomNode(a,b,c){b&&b.removeChild(a);c&&c.appendChild(a)}function tt_Err(a){tt_Debug&&alert("Tooltip Script Error Message:\n\n"+a)}function tt_ExtCmdEnum(){var a;for(var b in config){a="window."+b.toString().toUpperCase();if(eval("typeof("+a+") == tt_u")){eval(a+" = "+tt_aV.length);tt_aV[tt_aV.length]=null}}}function tt_ExtCallFncs(a,b){for(var c=false,d=tt_aExt.length;d;){--d;var e=tt_aExt[d]["On"+b];if(e&&e(a))c=true}return c}tt_Init();
