<?php
/*  Copyright 2009, ontoprise GmbH
*  This file is part of the Collaboration-Extension.
*
*   The Collaboration-Extension is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 3 of the License, or
*   (at your option) any later version.
*
*   The Collaboration-Extension is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/**
 * Maintenance script for setting up the database tables for Collaboration Extension
 * 
 * @author Benjamin Langguth
 * Date: 2009-10-16
 * 
 */
 
 //TODO: add script to convert local comments created by old Comments extension to new ones.
 
if (array_key_exists('SERVER_NAME', $_SERVER) && $_SERVER['SERVER_NAME'] != NULL) {
    echo "Invalid access! A maintenance script MUST NOT accessed from remote.";
    return;
}

$mediaWikiLocation = dirname(__FILE__) . '/../../..';
require_once "$mediaWikiLocation/maintenance/commandLine.inc";
$dir = dirname(__FILE__);
$cegIP = "$dir/../../Collaboration";

require_once("$cegIP/storage/CE_CommentsDBHelper.php");

$delete = array_key_exists('delete', $options);

if ($delete) {
	echo "Deleting database tables for Collaboration...\n";
	CEStorageSQL::dropDatabaseTables();
	echo "done.\n";
} else {
	echo "Setting up database tables for Collaboration...\n";
	CEStorageSQL::initDatabaseTables();
	echo "done.\n";
}

class CEStorageSQL {
	/**
	 * Initializes the database table of the Collaboration extension.
	 * This is:
	 * - rating:
	 * 		table of Extension:Rating Bar
	 */
	public function initDatabaseTables() {

		$db =& wfGetDB( DB_MASTER );

		$verbose = true;

		CEDBHelper::reportProgress("Setting up Collaboration ...\n",$verbose);

		//Rating Bar
		$table = $db->tableName('ce_ratingbar');
		CEDBHelper::setupTable($table, array(
			'user_id'		=> 'INT( 10 ) UNSIGNED NOT NULL',
			'rating'		=> 'TINYINT( 3 ) UNSIGNED NOT NULL',
			'page_id'		=> 'VARCHAR( 255 ) NOT NULL',
			'time'			=> 'INT( 10 ) NOT NULL',
			'ip'			=> 'VARBINARY( 40 ) NOT NULL'),
		$db, $verbose, 'user_id, rating, page_id, ip');
		CEDBHelper::reportProgress("   ... done!\n",$verbose);

		return true;
	}
	
	public function dropDatabaseTables() {
		global $wgDBtype;
		$verbose = true;
		
		CEDBHelper::reportProgress("Deleting all database content and tables generated by Collaboration ...\n\n",$verbose);
		$db =& wfGetDB( DB_MASTER );
		$tables = array(
			'ce_ratingbar');
		foreach ($tables as $table) {
			$name = $db->tableName($table);
			$db->query('DROP TABLE' . ($wgDBtype=='postgres'?'':' IF EXISTS'). $name, 'SMWSemanticStoreSQL2::drop');
			CEDBHelper::reportProgress(" ... dropped table $name.\n", $verbose);
		}
		CEDBHelper::reportProgress("All data removed successfully.\n",$verbose);
	}
}